### ISSUE TITLE
[ICL][BUG]HDMI has no sound output after wake up from s3 during HDMI playback

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1080]
**Describe the bug**
HDMI output no sound after wake up from s3 during HDMI playback. Besides, waking up from s3 was very slow.

**To Reproduce**

1.Connect HDMI external, and adjust alsamixer pin6-port0 to cvt3 
2.Play HDMI music(aplay -Dhw:0,3 -f dat 1.wav -vv -i)
3.Enter S3 then wake up

**frequency**

100%

**Expected result**
HDMI keep playing after wake up from s3

**Actual result**
Wake up from s3 very slowly and HDMI output no sound after s3 while console shows music is still playing.

**Environment**
Firmware: fcd72767 https://github.com/thesofproject/sof/commits/master
Kernel: 86b820f2 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
platform： icl-rvp

**dmesg**
```
[  204.850722] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[  204.850978] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[  204.866722] atkbd serio0: Failed to deactivate keyboard on isa0060/serio0
[  204.876602] nvme nvme0: 8/0/0 default/read/poll queues
[  204.947069] ata3: SATA link down (SStatus 4 SControl 300)
[  205.242972] atkbd serio0: Failed to enable keyboard on isa0060/serio0
[  205.350026] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  205.350063] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  205.850030] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  205.850068] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  206.578472] e1000e: enp0s31f6 NIC Link is Up 100 Mbps Full Duplex, Flow Control: None
[  206.578475] e1000e 0000:00:1f.6 enp0s31f6: 10/100 speed: disabling TSO
[  207.858991] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 4:0
[  207.858995] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[  207.859030] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 8:0
[  207.859033] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 10:0
[  207.859035] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 11:0
[  208.053484] sdhci-pci 0000:00:14.5: SDHCI controller found [8086:34f8] (rev 30)
[  208.054765] OOM killer enabled.
[  208.054767] Restarting tasks ... 
[  208.056626] sof-audio-pci 0000:00:1f.3: hda: prepare stream dir 0
[  208.056636] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  208.056759] done.
[  208.057018] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  208.057057] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[  208.057100] sof-audio-pci 0000:00:1f.3: pcm: prepare stream 3 dir 0
[  208.057102] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 3 dir 0
[  208.057116] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  208.057153] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  208.057158] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[  208.057159] sof-audio-pci 0000:00:1f.3: periods:4
[  208.057220] sof-audio-pci 0000:00:1f.3: stream_tag 1
[  208.057224] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  208.057449] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  208.057451] sof-audio-pci 0000:00:1f.3: pcm: stream dir 0, posn mailbox offset is 790528
[  208.057586] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 3 dir 0 cmd 1
[  208.057641] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[  208.057642] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  208.057849] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  208.057856] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[  208.101955] PM: suspend exit
[  208.299990] e1000e: enp0s31f6 NIC Link is Down
[  208.849715] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  208.849768] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  210.045803] e1000e: enp0s31f6 NIC Link is Up 100 Mbps Full Duplex, Flow Control: None
[  210.045810] e1000e 0000:00:1f.6 enp0s31f6: 10/100 speed: disabling TSO
[  210.045960] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s31f6: link becomes ready
[  213.848772] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:0
[  226.241015] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[  241.933970] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:0
[  271.991677] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 3 dir 0 cmd 0
[  271.992230] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[  271.992248] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  271.992378] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  271.992388] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=0
[  271.992549] sof-audio-pci 0000:00:1f.3: pcm: free stream 3 dir 0
[  271.992557] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  271.992709] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  271.992730] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  271.992872] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  271.992926] sof-audio-pci 0000:00:1f.3: pcm: close stream 3 dir 0
[  272.850146] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  272.850184] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  277.037556] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[  277.074047] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  277.074247] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  277.074356] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[  277.074360] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[  277.074363] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
```

[hdmi_sound_dmesg.log](https://github.com/thesofproject/linux/files/3362297/hdmi_sound_dmesg.log)
[hdmi_sound_logger.log](https://github.com/thesofproject/linux/files/3362298/hdmi_sound_logger.log)

**Comment by ClarexZhou** [comment]
Error also seen on DP.
linux (topic/sof-dev): 8b8f4377
sof (master): f837e57b
Platform: ICL HDA RVP

**Comment by kv2019i** [comment]
In progress, see comments in https://github.com/thesofproject/linux/issues/1104#issuecomment-520406205 
I believe rootcause is the same in both bugs.

**Comment by kv2019i** [comment]
https://github.com/thesofproject/linux/issues/1123 now ready for testing (take https://github.com/thesofproject/linux/pull/1155 and https://github.com/thesofproject/kconfig/pull/15 to test), should fix this bug

**Comment by ClarexZhou** [comment]
@kv2019i , thesofproject/kconfig#15  can't be applied as below.
```
scripts/kconfig/conf  --alldefconfig Kconfig
./.tmp.config.wooorQeqQp:4819:warning: unexpected data: SND_SOC_SOF_HDA_COMMON_HDMI_CODEC=y
```
And build sccuessfully with merge "CONFIG_SND_SOC_SOF_HDA_COMMON_HDMI_CODEC=y" config. Is this right?

But ICL always display no sound card when "aplay -l" to check after system boot up.
Check dmesg 
[pr1155_dmesg.txt](https://github.com/thesofproject/linux/files/3615050/pr1155_dmesg.txt)


CML HDA platform can work successfully, still under testing.

**Comment by YvonneYang2** [comment]
Met same aplay-l display no soundcards issue on cml hda notebook after module reload test. And now always cannot boot up successfully.

**Comment by kv2019i** [comment]
@ClarexZhou wrote: 
> @kv2019i , [thesofproject/kconfig#15](https://github.com/thesofproject/kconfig/pull/15) can't be applied as below.
[...]
> ./.tmp.config.wooorQeqQp:4819:warning: unexpected data: SND_SOC_SOF_HDA_COMMON_HDMI_CODEC=y

Ack, my bad, fixed now in 
https://github.com/thesofproject/kconfig/pull/15

> But ICL always display no sound card when "aplay -l" to check after system boot up.
> Check dmesg
> [pr1155_dmesg.txt](https://github.com/thesofproject/linux/files/3615050/pr1155_dmesg.txt)
> 
> CML HDA platform can work successfully, still under testing.

Hmm, ok. This is bug:
https://github.com/thesofproject/linux/issues/1184

... I have hit this on CFL as well, so not ICL specific, but seems to happen more often. As a temporary work-around (to enable other testing), the bug can be avoided by blacklisting the SOF module at boot and modprobe SOF "snd_sof_pci" module only after system has booted up. This seems to avoid issue 1184 . But this is only a temporary help. I will look into this issue.

FYI @YvonneYang2

**Comment by YvonneYang2** [comment]
Added SOF "snd_sof_pci" module in blacklist.conf, reboot system, then modprobe "snd_sof_pci" module. But it seems not work for both CML and ICL, module cannot load successfully, aplay -l still shows no soundcard.

Check dmesg:
[dmesg.log](https://github.com/thesofproject/linux/files/3618898/dmesg.log)

**Comment by kv2019i** [comment]
@YvonneYang2 wrote:
> Added SOF "snd_sof_pci" module in blacklist.conf, reboot system, then modprobe "snd_sof_pci" module. But it seems not work for both CML and ICL, module cannot load successfully, aplay -l still shows no soundcard.

Ack, will look into this. Based on the log, this seems like issue #1184 :
[  113.870011] snd_hda_codec_hdmi ehdaudio0D2: HDMI: failed to get afg sub nodes
[  113.870022] snd_hda_codec_hdmi ehdaudio0D2: patch failed -22
[  113.870113] snd_hda_codec_hdmi ehdaudio0D2: ASoC: failed to probe component -22

But it's very good data point this is happening more often with the new HDA-HDMI patchset.

**Comment by wenqingfu** [comment]
I see this start showing up on GLK as well in CI. Previously, the HDMI audio detection was quite stable on GLK_BOB, I would say.

**Comment by kv2019i** [comment]
This bug should be fixed with combination of patches to i915 driver and SOF. While waiting for patches to be accepted, can be tested with PR #1155

**Comment by dengyangchao** [comment]
issue is fixed by PR1304, close the issue
