### ISSUE TITLE
How do I install SOF under Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by katsar0v** [thesofproject/linux#1877]
This not a bug, but rather a feature request (maybe for docs). I have Dell Inspiron 7590 which has no microphone working when a fresh Ubuntu is installed (the 3.5mm jack does not work as well). ArchLinux -https://wiki.archlinux.org/index.php/Dell_Inspiron_15_(7590) says it works with the newest sof firmware, but how do I install it under Ubuntu?
I hope not every new Dell user has to clone this repo and clone it in order to get the mic working, but it would be much easier to install it via ppa or a .deb file. Thanks in advance, in case somebody decides to help me out here!

**Comment by plbossart** [comment]
Summary of the required changes:

0. update the kernel to v5.3

1. edit /etc/modprobe.d/alsa-base.conf to add 

blacklist snd-hda-intel
blacklist snd-soc-skl

2. fetch https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/sof-skl_hda_card 
and copy the directory to /usr/share/alsa/ucm

**Comment by katsar0v** [comment]
@plbossart correct, 0. is done via just `sudo apt update && sudo apt upgrade`. 1. and 2. were somehow unclear (or undocumented) for me. I also wasn't aware if sof was properly (or at all) installed. Let me know if I can help you further here.

**Comment by giorgionicoletti** [comment]
This solution worked wonderfully until yesterday on my Dell Inspiron 7590, Ubuntu 18.04 LTS and kernel v5.3.0-42. Today, on startup the sound stopped working altogether and Ubuntu was not detecting any soundcard (I could only see "Dummy output" in the settings). I don't recall doing anything particularly nor updating anything. I couldn't even open alsamixer (with error "cannot open mixer").

I had to remove the blacklist from /etc/modprobe.d/alsa-base.conf and add the option `snd-hda-intel dmic_detect=0`. Now I have the sound back but the internal microphone is not detected again (it is shown as unplugged in pavucontrol and no input is present in the settings). So it's back to square one.

If I blacklist `snd-hda-intel` and `snd-soc-skl` and run `lspci -nnk | grep -A2 audio` the kernel driver in use is sof-audio-pci, but I get only the dummy output, no sound nor mic and pavucontrol/Consiguration returns "no cards available for configuration".

I'm far from being an expert, so any help would be greatly appreciated. Thanks.

**Comment by kv2019i** [comment]
@giorgionicoletti wrote:
>  I don't recall doing anything particularly nor updating anything. I couldn't even open alsamixer (with error "cannot open mixer").

That hints at a problem in driver probe. Can you share output of alsa-info.sh (instructions https://wiki.ubuntu.com/Audio/AlsaInfo) when the problem happens?

**Comment by giorgionicoletti** [comment]
@kv2019i Sure, there you go: http://alsa-project.org/db/?f=b72bcfd31ec3695aa4bf23f28edc7408975f397a. This is the output I get when I add the two blacklist lines to alsa-base.conf and sounds stop working.

**Comment by katsar0v** [comment]
> This solution worked wonderfully until yesterday on my Dell Inspiron 7590, Ubuntu 18.04 LTS and kernel v5.3.0-42. Today, on startup the sound stopped working altogether and Ubuntu was not detecting any soundcard (I could only see "Dummy output" in the settings). I don't recall doing anything particularly nor updating anything. I couldn't even open alsamixer (with error "cannot open mixer").
> 
> I had to remove the blacklist from /etc/modprobe.d/alsa-base.conf and add the option `snd-hda-intel dmic_detect=0`. Now I have the sound back but the internal microphone is not detected again (it is shown as unplugged in pavucontrol and no input is present in the settings). So it's back to square one.
> 
> If I blacklist `snd-hda-intel` and `snd-soc-skl` and run `lspci -nnk | grep -A2 audio` the kernel driver in use is sof-audio-pci, but I get only the dummy output, no sound nor mic and pavucontrol/Consiguration returns "no cards available for configuration".
> 
> I'm far from being an expert, so any help would be greatly appreciated. Thanks.

I also see "dummy output" from times to times, but a reboot usually fixes it. Am using `5.3.0-40-generic` though

**Comment by giorgionicoletti** [comment]
> I also see "dummy output" from times to times, but a reboot usually fixes it. Am using `5.3.0-40-generic` though

Nope, unfortunately a reboot does not fix it. I think that I had `5.3.0-42-generic` all along though (I tried this solution no later than six days ago), so I can't really get my head around to what happened.

**Comment by Jeff406** [comment]
I have this laptop too, tried many times all the fixes available in arch linux (manjaro) with the latest kernel but no hope. The internal microphone is working unstably and all the issues are still not fixed as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1772498#c209 (view other comments). I think we'll have to wait for the update of sof-firmware and related ucm stuffs.

**Comment by kv2019i** [comment]
@giorgionicoletti wrote: 
> @kv2019i Sure, there you go: http://alsa-project.org/db/?f=b72bcfd31ec3695aa4bf23f28edc7408975f397a. 

Aa, ok. So this is something else, there's actually kernel error hit when registering the card:

RIP: 0010:skl_hda_hdmi_jack_init 0x3f/0x110 [snd_soc_skl_hda_dsp]

Could you post full dmesg and your kernel config (.config or config file in /boot your distro has shipped)? The oops is on a code path related to the hdac-hdmi driver. We switched to different codec driver in 5.5. So it could be a bug specific to 5.3/5.4. With dmesg+config I can confirm this.

**Comment by plbossart** [comment]
@giorgionicoletti looks like an ubuntu kernel update gone wrong. Can you try and boot from a previous version with the "advanced options" grub menu and select 5.3.0-40-generic which seemed to work before?

**Comment by giorgionicoletti** [comment]
@plbossart you're right! I thought I checked and did not update the kernel, but apparently I was wrong. Booting 5.30.0-40 seems to work as before.

**Comment by plbossart** [comment]
ok it's probably an Ubuntu kernel update that's missing backported patches or not using the right configuration. @jason77-wang is this something you can help with?

**Comment by giorgionicoletti** [comment]
> Aa, ok. So this is something else, there's actually kernel error hit when registering the card:
> 
> RIP: 0010:skl_hda_hdmi_jack_init 0x3f/0x110 [snd_soc_skl_hda_dsp]
> 
> Could you post full dmesg and your kernel config (.config or config file in /boot your distro has shipped)? The oops is on a code path related to the hdac-hdmi driver. We switched to different codec driver in 5.5. So it could be a bug specific to 5.3/5.4. With dmesg+config I can confirm this.

In case you still need them, I'm uploading both the full dmesg and the config file of 5.30.0-42.

[dmesg.txt](https://github.com/thesofproject/linux/files/4350775/dmesg.txt)

[kernel-config.txt](https://github.com/thesofproject/linux/files/4350778/kernel-config.txt)

**Comment by plbossart** [comment]
@giorgionicoletti it's pretty clear it's an issue with HDMI, but we'd need to see what changed in the Ubuntu kernel tree between 5.30.0-40 and 5.30.0-42. I don't know where the git tree is personally.

**Comment by giorgionicoletti** [comment]
> @giorgionicoletti it's pretty clear it's an issue with HDMI, but we'd need to see what changed in the Ubuntu kernel tree between 5.30.0-40 and 5.30.0-42. I don't know where the git tree is personally.

I think I will roll back to 5.30.0-40 for the time being since I'm also noticing other weird things going on (the system hangs on reboot most of the time). However, if you need anything please ask. I really appreciate your help!

**Comment by kv2019i** [comment]
Ok thanks @giorgionicoletti . It seems 5.30.0-42 enables the common HDMI driver (i.e. backports the patchset from upstream 5.5):

http://changelogs.ubuntu.com/changelogs/pool/main/l/linux/linux_5.3.0-42.34/changelog

alsa/sof: change to use hda hdmi codec driver to make hdmi audio on the
    docking station work (LP: #1855666)
    - ALSA: hda/hdmi - implement mst_no_extra_pcms flag
    - ASoC: hdac_hda: add support for HDMI/DP as a HDA codec
    - ASoC: Intel: skl-hda-dsp-generic: use snd-hda-codec-hdmi
    - ASoC: Intel: skl-hda-dsp-generic: fix include guard name
    - ASoC: SOF: Intel: add support for snd-hda-codec-hdmi
    - ASoC: Intel: bxt-da7219-max98357a: common hdmi codec support
    - ASoC: Intel: glk_rt5682_max98357a: common hdmi codec support
    - ASoC: intel: sof_rt5682: common hdmi codec support
    - ASoC: Intel: bxt_rt298: common hdmi codec support
    - ASoC: SOF: enable sync_write in hdac_bus
    - [config]: SND_SOC_SOF_HDA_COMMON_HDMI_CO

I can see also that in the kconfig you uploaded, the COMMON_HDMI_CODEC option is correctly set:

kernel-config.txt:
CONFIG_SND_SOC_SOF_HDA_COMMON_HDMI_CODEC=y

But in the kernel oops, code hits a path that is only run if the new HDMI codec is disabled (which should not happen). Let me dig this a bit.

**Comment by kv2019i** [comment]
@giorgionicoletti Ok, problem rootcaused. I took the same Ubuntu-5.3.0-42.34 kernel and could reproduce it on of my test devices. 

Rootcause for failure is this missing patch from the backport:
8ce1cbd6ce0 ASoC: topology: fix soc_tplg_fe_link_create() - link->dobj initialization order

Essentially ASoC core did not call "add_dai_link" callbacks, so the HDMI PCM nodes did not get added. The error was made worse by a missing check on existance of PCM nodes. This too is fixed in Linux upstream (with upstream, a similar bug would have just disabled HDMI).

So in short, this is a bug specific to Ubuntu kernels. I can see this is fixed eoan kernel Ubuntu-5.3.0-43.36  (https://bugs.launchpad.net/bugs/1864061).

**Comment by kv2019i** [comment]
@Jeff406 wrote:
> I have this laptop too, tried many times all the fixes available in arch linux (manjaro) with 
> the latest kernel but no hope. The internal microphone is working unstably and all 
> the issues are still not fixed as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1772498#c209 (view other comments). 
>  I think we'll have to wait for the update of sof-firmware and related ucm stuffs.

It's a bit hard to act on this info. There are a number of things out of our control in SOF, including the audio codec drivers, pulseaudio integration and packaging of the firmware files for each kernel version. But in general, if a laptop works with one distro, it really should work with others as well, or there is some distro specific issue (that should be fixable by copying the solution from other distros). Based on your info, you have a laptop that should work now. The Redhat/Fedora bug you refer to is closed as fixed. Similarly for Ubuntu, based on above latest 19.10 kernel will work with SOF. For Arch/Manjaro, I found at least this: https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_7)#Audio .. stating it is working.

If there is a specific problem in SOF drivers or firmware, we can try to help, but without specifics, we can't really do that.

**Comment by giorgionicoletti** [comment]
> @giorgionicoletti Ok, problem rootcaused. I took the same Ubuntu-5.3.0-42.34 kernel and could reproduce it on of my test devices.
> 
> Rootcause for failure is this missing patch from the backport:
> [8ce1cbd](https://github.com/thesofproject/linux/commit/8ce1cbd6ce0b1bda0c980c64fee4c1e1378355f1) ASoC: topology: fix soc_tplg_fe_link_create() - link->dobj initialization order
> 
> Essentially ASoC core did not call "add_dai_link" callbacks, so the HDMI PCM nodes did not get added. The error was made worse by a missing check on existance of PCM nodes. This too is fixed in Linux upstream (with upstream, a similar bug would have just disabled HDMI).
> 
> So in short, this is a bug specific to Ubuntu kernels. I can see this is fixed eoan kernel Ubuntu-5.3.0-43.36 (https://bugs.launchpad.net/bugs/1864061).

Great. Thank you very much!

**Comment by armantorkzaban** [comment]
Is there a way to install SOF under Debian Bullseye (5.4.0-4-amd64) ?
I would like to participate as a tester if possible. 
Device info: 

00:1f.3 Multimedia audio controller [0401]: Intel Corporation Cannon Lake PCH cAVS [8086:a348] (rev 10)
        DeviceName: Onboard - Sound
        Subsystem: Dell Cannon Lake PCH cAVS [1028:0924]

**Comment by plbossart** [comment]
@armantorkzaban do you have DMICs available on this device? You should see something in the dmesg log related to microphones.

If yes, you will need to install the firmware and topology (from https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2) and see how this works.

**Comment by armantorkzaban** [comment]
The only things related to "Mic" are these:
[   11.160166] snd_hda_codec_realtek hdaudioC0D0:      Headphone Mic=0x1b
[   11.160167] snd_hda_codec_realtek hdaudioC0D0:      Headset Mic=0x19
[   11.263365] input: HDA Intel PCH Headphone Mic as /devices/pci0000:00/0000:00:1f.3/sound/card0/input27

Do they count?

**Comment by katsar0v** [comment]
![image](https://user-images.githubusercontent.com/7236157/77231347-95c3e380-6b9a-11ea-89b4-5d9c062772ce.png)

So I got the kernel `5.3.0-42-generic` as well and see only this, just to confirm. Is there 43 for Ubuntu 18?

**Comment by astromatt42** [comment]
Hi, I am experiencing the same issues on LM 19.3 (based on 18.04) with kernel 5.3.0-40 (5.3.0-42 causes many other issues hence I am sticking with -40 for now)
I have followed the suggested steps by blacklisting the two drivers and copying the SOF files in the appropriate directory - this results in no sound and no mic.
However there may be a hint here, blacklisting and removing the folder with the SOF files brings sound back but no mic. Does this mean that something goes belly up when these files are loaded by the kernel?

DMESG with the files: https://pastebin.com/uPvLv8St

DMESG without the files: https://pastebin.com/7uwYxKDj

alsa-info output: https://alsa-project.org/db/?f=164f61033f3d90808c4f7f072c4e234628e8a9ff

I wish I was better at troubleshooting these things.
Thanks for your help,

Matt

**Comment by kv2019i** [comment]
@katsar0v @mattmax42 Probably in both of your cases, you now have the kernel drivers correctly loading, but you are missing the ALSA UCM files, so Pulseaudio cannot find the sound devices. Please see https://github.com/thesofproject/linux/issues/1877#issuecomment-596600017 for how to do this on older distros.

@mattmax42 That is expected. When you remove the blacklisting, your system goes back to using the older snd-hda-intel driver where the audio DSP is bypassed (the hardware supports usage with and without the DSP). This drive does not support directly connected digital microphones, and on a system like yours, this means microphone won't work. Your system has UCM files for this driver, so Pulseaudio otherwise works.

When you add the blacklist rule, the DSP-enabled SOF driver is loaded (your alsa-info log shows the driver is ok), but as you don't have the UCM files installed, Pulseaudio cannot find the sound devices.

**Comment by astromatt42** [comment]
HI, sorry maybe I wasn't quite clear enough:
I have blacklisted the two drivers and copied the UCM files as suggested in the post. lscpi reports sof-audio-pci as the Kernel driver in use, however no sound, no mic. I get a dummy output and no input devices.
If I keep the blacklisting but remove the files, I get at least my output back.

The relevant lines in the dmesg output for the situation with the blacklisting and the files in place:

https://pastebin.com/AmBCagqB

Thanks,

Matt

**Comment by astromatt42** [comment]
Ok, having just rebooted with the files deleted but the blacklist in place: It loads the sof-audio-pci driver, I have a working output device ('sof-skl_hda_card' and 'Multichannel Output sof-skl_hda_card') an input device is listed as 'Multichannel Input sof-skl_hda_card' but does not work. To me this looks like it must be loading the UCM files from somewhere else but maybe hasn't got the right files for the mic?

**Comment by kv2019i** [comment]
@mattmax42 Aa, sorry, I jumped to conclusions a bit too quickly. I thought by files you just meant the firmware files, but ok, you had copied UCM as well. The kernel driver and FW is definitely working based on your alsa-info dump ealier:
```
APLAY

**** List of PLAYBACK Hardware Devices ****
card 0: sofsklhdacard [sof-skl_hda_card], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsklhdacard [sof-skl_hda_card], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsklhdacard [sof-skl_hda_card], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsklhdacard [sof-skl_hda_card], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsklhdacard [sof-skl_hda_card], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

ARECORD

**** List of CAPTURE Hardware Devices ****
card 0: sofsklhdacard [sof-skl_hda_card], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsklhdacard [sof-skl_hda_card], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

So something goes wrong in Pulseaudio and how it interprets the UCM files. To debug this, we'd need to see the PA logs -- see https://github.com/thesofproject/linux/issues/1877#issuecomment-595993787 for instructions.

**Comment by astromatt42** [comment]
Thanks Kai and no worries, see attached:
[log_1.txt](https://github.com/thesofproject/linux/files/4369573/log_1.txt)

**Comment by plbossart** [comment]
@mattmax42 did you follow the recommended instruction above for UCM/PulseAudio?

fetch https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/sof-skl_hda_card
and copy the directory to /usr/share/alsa/ucm

**Comment by astromatt42** [comment]
@plbossart yes, have a look:

(base) mar@mar-Inspiron-7591-2n1:~$ cd /usr/share/alsa/ucm/

(base) mar@mar-Inspiron-7591-2n1:/usr/share/alsa/ucm$ ls
apq8064-tabla-snd-card  HDAudio-Lenovo-DualCodecs   SDP4430
broadwell-rt286         Manta-I2S                   skylake-rt286
chtrt5645               Manta-SPDIF                 sof-skl_hda_card
DAISY-I2S               msm8974-taiko-mtp-snd-card  tegraalc5632
DB410c                  PandaBoard                  tegra-rt5640
Dell-WD15-Dock          PandaBoardES                Tuna
GoogleNyan              PAZ00                       VEYRON-I2S

(base) mar@mar-Inspiron-7591-2n1:/usr/share/alsa/ucm$ cd sof-skl_hda_card/

(base) mar@mar-Inspiron-7591-2n1:/usr/share/alsa/ucm/sof-skl_hda_card$ ls
Hdmi1.conf  Hdmi3.conf     HiFi.conf  sof-skl_hda_card.conf
Hdmi2.conf  HdmiHdac.conf  Mics.conf

**Comment by plbossart** [comment]
@mattmax42 did you mean that you copied the files,  or that they were present already with Ubuntu?

Also can you check that you have DMIC capture devices with arecord -l. If you don't then either the topology is wrong, or you don't have DMICS...

**Comment by astromatt42** [comment]
@plbossart Yes I copied the files as you suggested, there was no folder with the same name in the directory before. Output of arecord -l:

(base) mar@mar-Inspiron-7591-2n1:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofsklhdacard [sof-skl_hda_card], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsklhdacard [sof-skl_hda_card], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

I should also mention again, I find it suspicious that when I remove the UCM files again, i.e. delete the folder I have previously copied to /usr/share/alsa/ucm, it still seems to load the sof kernel driver. Does this mean that it fetches the files from somewhere else? This gives me working output, shows and input device which doesn't work though. Could this be a version or multiple driver conflict? It is LM 19.3 by the way, so Ubuntu 18.04 really, could they have packaged other drivers with the distro?

**Comment by plbossart** [comment]
@mattmax42 forget UCM for now, if you don't have a DMIC capture device then something else is problematic.

**Comment by paulstelian97** [comment]
UCM shouldn't affect aplay and the kernel driver, but how pulseaudio uses them.

**Comment by astromatt42** [comment]
Thanks all, to troubleshoot a bit further, dmesg | grep dmic:
[    3.672874] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link dmic01
[    3.672875] skl_hda_dsp_generic skl_hda_dsp_generic: info: override FE DAI link dmic16k
[    3.776793] skl_hda_dsp_generic skl_hda_dsp_generic: dmic-hifi <-> DMIC01 Pin mapping ok
[    3.776801] skl_hda_dsp_generic skl_hda_dsp_generic: dmic-hifi <-> DMIC16k Pin mapping ok

Edit:
Following an update of libasound2, sound output is working again with the files in place.

**Comment by kv2019i** [comment]
@mattmax42 Ack, good point @plbossart I had missed that the DMIC were not in "arecord -l" list. And, indeed the problem is the missing DMIC devices. Pulseaudio will log an error for each DMIC node and fails to load the profiles. In the log you shared, it's this:
E: [pulseaudio] module-alsa-card.c: Failed to find a working profile.

**Comment by kv2019i** [comment]
@plbossart Hmm, need to check past bugs, but there's nothing obvious in the logs. The kernel version is old compared to the loaded tplg (8 vs  11), but I just checked that the last change to dmic tokens was at ABI 8, so this kernel already has it. The dmic-codec is there, so looks all good.

@mattmax42 wrote:
> Following an update of libasound2, sound output is working again with the files in place.

Hmm, interesting, so everything solved now? Do you see DMIC entries in "arecord -l"?

**Comment by Jeff406** [comment]
> @Jeff406 wrote:
> 
> > I have this laptop too, tried many times all the fixes available in arch linux (manjaro) with
> > the latest kernel but no hope. The internal microphone is working unstably and all
> > the issues are still not fixed as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1772498#c209 (view other comments).
> > I think we'll have to wait for the update of sof-firmware and related ucm stuffs.
> 
> It's a bit hard to act on this info. There are a number of things out of our control in SOF, including the audio codec drivers, pulseaudio integration and packaging of the firmware files for each kernel version. But in general, if a laptop works with one distro, it really should work with others as well, or there is some distro specific issue (that should be fixable by copying the solution from other distros). Based on your info, you have a laptop that should work now. The Redhat/Fedora bug you refer to is closed as fixed. Similarly for Ubuntu, based on above latest 19.10 kernel will work with SOF. For Arch/Manjaro, I found at least this: https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_7)#Audio .. stating it is working.
> 
> If there is a specific problem in SOF drivers or firmware, we can try to help, but without specifics, we can't really do that.

Hi @kv2019i ,
In case you can help, here is my alsa-info http://alsa-project.org/db/?f=12c2331125d38c5aee7c4830da5bfc49d6bb7aee
and dmesg
[dmesg-20200322-2.txt](https://github.com/thesofproject/linux/files/4375240/dmesg-20200322-2.txt)
Thanks for your response.

**Comment by astromatt42** [comment]
@kv2019i Hi, unfortunately not, in fact it has gotten worse, while audio output works, still no mic and now the machine refuses to wake after sleep - so there must be some interaction with libasound2. Removing all mods and going back to the intel driver helps, so I am tempted to shelve this for now until a newer Kernel/new drivers are released and then try again...

**Comment by armantorkzaban** [comment]
> UCM shouldn't affect aplay and the kernel driver, but how pulseaudio uses them.

@paulstelian97  I have DMIC and I can capture sound by arecord. 
How can set the pulseaudio UCM for: 

- sofhdadsp [sof-hda-dsp]

- 00:1f.3 Multimedia audio controller [0401]: Intel Corporation Cannon Lake PCH cAVS [8086:a348] (rev 10)
        Subsystem: Dell Cannon Lake PCH cAVS [1028:0924]
        Kernel driver in use: sof-audio-pci
        Kernel modules: snd_hda_intel, snd_sof_pci
00:1f.4 SMBus [0c05]: Intel Corporation Cannon Lake PCH SMBus Controller [8086:a323] (rev 10)

**Comment by hoo2** [comment]
I'm running ubuntu 19.10 and i can confirm:

1) The solution with blacklist of "snd-hda-intel" and "snd-soc-skl" and [ucm directory](https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/sof-skl_hda_card) copy to /usr/share/alsa/ucm/, is working for 5.3.0-40-generic. It only needs some alsamixer boost for mic.

2) The 5.3.0-42-generic update does not work. Its faltback to DummyOutput device.

If someone need any help, log, dump or something let me know. I could help.

**Comment by kv2019i** [comment]
@mattmax42 wrote:
> @kv2019i Hi, unfortunately not, in fact it has gotten worse, while audio output works, still no mic and now the machine refuses to wake after sleep - so there must be some interaction with libasound2. 

Ack. The libsound2 update may break if you had manually copied UCM files to /usr/share/ucm. But the main problem is DMIC not visible in "arecord -l ".

> Removing all mods and going back to the intel driver helps, so I am tempted to shelve this > for now until a newer Kernel/new drivers are released and then try again...

Ack ,that is understandable, thanks a lot for all the debugging you've done so far. I would assume we'd get reports from other people as well to the dmic problem. That should help to figure out the rootcause. If anyone else has a similar 7591 Inspiron as @mattmax42 , it would be interesting to get reports, especially with a more recent kernel.

**Comment by kv2019i** [comment]
@Jeff406 wrote:
> In case you can help, here is my alsa-info http://alsa-project.org/db/?f=12c2331125d38c5aee7c4830da5bfc49d6bb7aee
> and dmesg
> [dmesg-20200322-2.txt](https://github.com/thesofproject/linux/files/4375240/dmesg-20200322-2.txt)

Hmm, it seems the two files are from separate boots. The alsa-info shows the "legacy driver" (snd_hda_intel) to be used and everything seems normal (but the digital mic is not supported by this driver, so that is missing). In the dmesg, I can see the SOF driver (that uses the DSP and can support the digital mic) is loaded, but there are no errors.

I'd be curious to see alsa-info about in the case matching the dmesg, e.g. when you have loaded the SOF driver. This is pretty close to the device @mattmax42 has, so e.g. interesting to see whether you have the DMIC device in "arecord -l". If it's missing, Pulseaudio cannot load the UCM and you see "Dummy" audio in the Sound Settings.

**Comment by astromatt42** [comment]
Having just tested these fixes with kernel 5.3.0-46, I can report that output and intput are now working. arecord -l also finds two DMICs. The only issue that remains are the freezes on wake from sleep. I have attached a new dmesg in case it is helpful and I am trying to find out how best to save logs from the freezes so they are available post reset.

https://pastebin.com/znvxaZUR

N.b. this relates to bug https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1869799

**Comment by plbossart** [comment]
@mattmax42 I don't understand the recommendation to use snd_hda_intel.dmic_detect=0
That would essentially prevent SOF from working?

FWIW we did have HDAudio freezes during the Summer 2019, I don't think the fixes were added to 5.3-stable. @kv2019i @ranj063 does this ring a bell.

**Comment by astromatt42** [comment]
@plbossart The snd_hda_intel.dmic_detect=0 parameter is  -not- set. It does completely disable the dmics, so resolves any crashes but as suggested it disables all inputs on my machine. Apart from the blacklisting and copying the UCM files, nothing else is set or done specifically to resolve any sound issues. -46 seems to have fixed some kernel-side driver issues, hence I guess why it is working now with the sof files and the blacklist in place, but like I said, the freeze on wake on sleep issue remains unfortunately.

**Comment by audunmb** [comment]
With some research I ended here, and followed the steps above (blacklisting in alsa.conf to enable SOF). I'm on Ubuntu 19.10.

There was a sof-skl_hda_card directory in /usr/share/alsa/ucm, but I tried with the files from github instead there. My soundcard doesn't show up at all with this setup. 
alsa-info http://alsa-project.org/db/?f=a947704e04b9188de40bf424fbe1e62dc5b448ee

With 
options snd-hda-intel dmic_detect=0
options snd-hda-intel index=0 model=laptop-dmic
in alsa.conf I have sound (but it seems that not all speakers are used), but no microphone.

Is there anything else I can do to get this working?

**Comment by hoo2** [comment]
@audunmb Did you tried : https://askubuntu.com/questions/1213271/microphone-does-not-work-on-new-dell-inspiron-7590/1220414#1220414 ?
I haven't test the newer kernel patches for 5.3.0 after *-42, but maybe you can do it, while you playing around.
For sure this method works for -40 and does not require:
> options snd-hda-intel dmic_detect=0
> options snd-hda-intel index=0 model=laptop-dmic

I aslo think [this](https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1859246) is also relevant.

**Comment by audunmb** [comment]
@hoo2 thanks, but that doesn't seem to work. Though I only have -46 and -45 installed. I'll upgrade to 20.4 and try again with a newer kernel.

If anyone is interested for debugging purposes. this is my alsa-info with the snd-hda-intel drivers not blacklisted http://alsa-project.org/db/?f=b1ec3c18bf56260f010b6fd01c9b008a6a623655

**Comment by Jeff406** [comment]
HI @kv2019i, 
Because you mentioned in https://github.com/thesofproject/linux/issues/1917, do you know when the new version of SOF will be released? As those who have the Inspiron 7590 ( especially with discrete nVidia card) got issues with DMIC and sound.

**Comment by audunmb** [comment]
I updated to 20.04, now on kernel 5.4.0-26, but it seems like SOF doesn't load even with blacklisting. 
lscpi -nnk | grep audio shows:
00:1f.3 Multimedia audio controller: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
	Subsystem: Hewlett-Packard Company Sunrise Point-LP HD Audio
	Kernel modules: snd_hda_intel
Also tried dmesg | grep sof, but only some references to microsoft showed there.

**Comment by hoo2** [comment]
@audunmb -42 and -45 was tested by me also and failed. So for now I use -40 and I wont upgrade to 20.4 if I can not be sure about the kernel.
Is there any way to install -40 on your system?

**Comment by kv2019i** [comment]
@Jeff406 wrote:
> Because you mentioned in #1917, do you know when the new version of SOF will be released? 

The final 1.5 was now tagged at https://github.com/thesofproject/sof/releases . The production signed binaries should be available next week the latest, if not sooner -> https://github.com/thesofproject/sof-bin/branches

**Comment by kv2019i** [comment]
@audunmb wrote:
> I updated to 20.04, now on kernel 5.4.0-26, but it seems like SOF doesn't load even with blacklisting.

Most machines with dmic and a HDA codec, should work out-of-the-box with 20.04 with no additional settings needed. SOF should be selected automatically. Only known big gap currently is laptops with hybrid Nvidia/Intel graphics. For these, both update to alsa-ucm-conf and a FW update is needed (more details in #1985 ).

The alsa-info you attached earlier is from 19.10, but I think the problem you have is dmic_detect=0 setting you have:
http://alsa-project.org/db/?f=b1ec3c18bf56260f010b6fd01c9b008a6a623655

... by doing this you force SOF to be disabled. Better to not set this parameter at all as it is deprecated (or set it to 1).

**Comment by kv2019i** [comment]
@hoo2 wrote:
> I haven't test the newer kernel patches for 5.3.0 after *-42, but maybe you can do it, while you playing around.

For anyone stuck in 18.04/19.x for reason another, the 5.3.0 kernel problem was fixed in Ubuntu-5.3.0-43.36 kernel (see https://github.com/thesofproject/linux/issues/1877#issuecomment-601219956). So stay at -40, update to -43.36, or upgrade distro to 20.04 -- all should work.

**Comment by Jeff406** [comment]
> @Jeff406 wrote:
> 
> > Because you mentioned in #1917, do you know when the new version of SOF will be released?
> 
> The final 1.5 was now tagged at https://github.com/thesofproject/sof/releases . The production signed binaries should be available next week the latest, if not sooner -> https://github.com/thesofproject/sof-bin/branches

It's good to hear that. Thanks for your information @kv2019i

**Comment by audunmb** [comment]
@kv2019i yes. that alsa-info was with that driver enabled, and working sound.
I still can't get this to work with. With 20.4 I get the following:

without any modifications in alsa-base.conf I have sound (Analog stereo according to Ubuntu settings), but no mic is detected

with 
options snd-hda-intel dmic_detect=0
options snd-hda-intel index=0 model=laptop-dmic
I get more options for sound (4 channels, 2 channels, stereo) in Ubuntu settings and it reports that I have "rear mic built-in". There's sound, and it seems like the mic notices something, but it doesn't work with arecord.

With 
blacklist snd-hda-intel
blacklist snd-soc-skl
I have no sound, and only "Dummy output" in Ubuntu settings. Alsamixer reports no soundcard.

**Comment by kv2019i** [comment]
> @kv2019i yes. that alsa-info was with that driver enabled, and working sound.
> I still can't get this to work with. With 20.4 I get the following:
> 
> without any modifications in alsa-base.conf I have sound (Analog stereo according to Ubuntu settings), but no mic is detected

Boot dmesg and alsa-info output would be interesting from this scenario. 

It could be the dmic detection from ACPI tables is not working on your machine. Another possibility is that your machine simply doesn't have a PCH digital mic, but rather the microphone is connected to the HDA codec and there is some problem with the ALC285 codec driver that prevents your mic from working. I.e. you don't need SOF, but need a fix to the Realtek codec driver. I can't say for sure which is the case based on current logs.

**Comment by kv2019i** [comment]
@Jeff406 v1.5 firmware is now available for testing (for the freeze problem):
https://github.com/thesofproject/sof-bin/tree/stable-v1.5

**Comment by kv2019i** [comment]
No new feedback in last two weeks and 20.04LTS has been out for some weeks as well now, so I think we have no need for this issue anymore. Thanks for all contributors!

**Comment by Jeff406** [comment]
> @Jeff406 v1.5 firmware is now available for testing (for the freeze problem):
> https://github.com/thesofproject/sof-bin/tree/stable-v1.5

can't wait to test this on my laptop. I will report back for the freeze issue.
Thanks for all your work - sof team.

**Comment by Jeff406** [comment]
> > @Jeff406 v1.5 firmware is now available for testing (for the freeze problem):
> > https://github.com/thesofproject/sof-bin/tree/stable-v1.5
> 
> can't wait to test this on my laptop. I will report back for the freeze issue.
> Thanks for all your work - sof team.

Confirm it works perfectly now on my Dell Vostro 7590 with discrete nVidia card

**Comment by hoo2** [comment]
So in order to make it work with 20.04 + Hybrid-nvidia(Inspiron 7590) we need:
 - Blacklist snd-hda-intel and snd-soc-skl
 - Custom alsa-ucm-conf files in /usr/share/alsa/ucm/
 - Update fw to v1.5 via some method that I have to find out...

?????

**Comment by Jeff406** [comment]
As release note for v1.5
**Recommended Linux recipe**

- Linux stable kernel 5.6.3 or newer, support for HD-Audio and PCH DMIC support on Intel Comet Lake and Tiger Lake
- alsa-lib 1.2.1.2 or newer
- alsa-ucm-conf 1.2.1.2 or newer
- Pulseaudio 13 or newer is nice to have, but not mandatory as long as it is built against new enough alsa-lib.

For those with ### options snd-intel-dspcfg dsp_driver=1 in /etc/modprobe.d/*.conf don't forget to remove it. ucm2 should be used also.

**Comment by kv2019i** [comment]
@hoo2 wrote:
> So in order to make it work with 20.04 + Hybrid-nvidia(Inspiron 7590) we need:
>     * Blacklist snd-hda-intel and snd-soc-skl

This is not needed.

>     * Custom alsa-ucm-conf files in /usr/share/alsa/ucm/

This will come to Ubuntu (and other distros) via upgrade of alsa-lib. The fix is already merged upstream.

>     * Update fw to v1.5 via some method that I have to find out...

The FW will be updated to Feroda and Ubuntu via normal channels. We are planning to release a 1.4.3 version with the same fix. Sof-bin repository contains instructions how to update the FW manually, but this is primarily intended and distribution packagers.

**Comment by imjuzcy** [comment]
I'm sorry for bumping this year old thread, but I just installed 20.04 LTS in the same laptop Inspiron 7590, with hybrid graphics. The previous comment by @kv2019i suggests that it should already be fixed, yet it still did not work out of the box. 

By default snd-hda-intel is used, and I have Dummy Out put as speaker. With detect_dmic=0 I can get speakers, but no microphone of course.

By blacklisting snd-hda-intel and snd-soc-skl and removing detect_dmic=0, I got sof-audio-pci as kernel driver in used. The first reboot seem to get me both speakers and mic, but after letting the laptop idle and went to suspend, it did not suspend successfully and froze with black screen (I suspect kernel panic). After a forced reboot I got back Dummy Output while kernel driver is still snd-audio-pci. 

In dmesg I found 
```
[    3.417795] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    3.417955] sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    3.417988] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[    3.418208] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.505699] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    4.512418] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[    4.537460] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[    4.537462] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    4.537467] sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 2
[    4.538641] sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 6 size 0x20
[    4.538643] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:8:0-8d1a5
[    4.538644] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:17:0
[    4.538645] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    4.538649] sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 3 size 0x30
[    4.538650] sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 5 size 0x20
[    4.681410] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:8:0-8d1a5
[    4.681411] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:17:0
[    4.681412] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    4.688847] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:18:1 Kernel ABI 3:17:0
[    4.688848] sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    4.696872] sof-audio-pci 0000:00:1f.3: error: reply expected 20 got 0 bytes
[    4.696929] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x30200000 size 20
[    4.696938] sof-audio-pci 0000:00:1f.3: error: buffer BUF7.0 load failed
[    4.696940] sof-audio-pci 0000:00:1f.3: error: DSP failed to add widget id 0 type 31 name : BUF7.0 stream none reply 0
[    4.696942] sof-audio-pci 0000:00:1f.3: ASoC: failed to load widget BUF7.0
[    4.696943] sof-audio-pci 0000:00:1f.3: ASoC: topology: could not load header: -22
[    4.697220] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -22
[    4.697224] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[    4.697225] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[    4.697226] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[    4.697238] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: failed to instantiate card -22
[    4.697285] skl_hda_dsp_generic: probe of skl_hda_dsp_generic failed with error -22
```
I have kernel 5.10.0-1034-oem and installed sof-bin v1.8.x/v1.8-rc2. How should I proceed?

Edit: aplay -l and arecord -l says no soundcard found. And on some reboots it will not boot at all, stucking at Ubuntu loading screen (before login screen)

**Comment by plbossart** [comment]
@ImjuzCY can you try to add this file as /etc/modprobe.d/sof-dyndgb.conf 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/6769883/sof-dyndbg.conf.txt)
reboot and attach the dmesg logs (not paste).

It's very odd that you would have such a topology issue, this may point to an install problem or a topology/firmware that isn't backwards-compatible with kernel 5.10 - which isn't good at all.

**Comment by kv2019i** [comment]
@ImjuzCY In addition to providing the logs, could you also try with a 21.04 live image? Did you upgrade to 20.04LTS in place? Based on the dmesg, SOF should be chosen even without any blacklisting, so something's not quite right in the installation. Ubuntu still ships 1.6 SOF by default, did you first try with this? The errors are not about i915/hybrid, so this is potentially a new issue. Let's try to figure out whether it's something related to your hw, or sw-config issue.
