### ISSUE TITLE
[BUG][CML]Arecord0,4 rt715 captured audio files output pop noise 

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1969]
**Describe the bug**
Arecord0,4 rt715 captured audio files have overshoot noise output at the beginning.

Captured audio files:
[audio file.zip](https://github.com/thesofproject/linux/files/4412787/audio.file.zip)

**To Reproduce**
1.Boot up system successfully.
2. Arecord -Dhw:0,4 -fs16_le -c2 -r 48000 -vv -i 00.wav
3. Check captured audio files 00.wav

**Reproduce rate**
5/5

**Expected result**
Arecord0,4 rt715 should captured audio files normally, no noise.

**Actual result**
Arecord0,4 rt715 captured audio files have pop noise output at beginning.

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:https://github.com/thesofproject/linux/commit/3bdd89d2d14f841700eb219e97c22a55aa414da0
FW: https://github.com/thesofproject/sof/commits/master commit: https://github.com/thesofproject/sof/commit/1e39ceec78b6150f4567e2631bc380762351bbdc
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

<img width="299" alt="3" src="https://user-images.githubusercontent.com/56706782/78099239-d54cc400-7413-11ea-833e-21c9d2401a09.PNG">

<img width="428" alt="2" src="https://user-images.githubusercontent.com/56706782/78099138-94ed4600-7413-11ea-90cc-83cba76f4161.PNG">

[dmesg1.log](https://github.com/thesofproject/linux/files/4412795/dmesg1.log) no error info in dmesg.

**Comment by plbossart** [comment]
what does "po" mean?

**Comment by plbossart** [comment]
@sinahuang isn't this fixed now? can we close?

**Comment by sinahuang** [comment]
Issue still can be reproduced with sof-dev(commit:  0d22f66) +master(commit :caae629) on CML-H.

**Comment by plbossart** [comment]
Indeed this doesn't look very good, see what I capture on my side.

![rt715](https://user-images.githubusercontent.com/1149035/84188696-a416f280-aa59-11ea-97a9-ab0d9bfb5e82.png)

@singalsu can you take a look? Maybe borrow @kv2019i 's SoundWire laptop to see what happens on the capture side?

**Comment by singalsu** [comment]
@plbossart Yup, it looks strange. I'll get such device and test.

**Comment by singalsu** [comment]
I have a suitable device now. The volume capture ramp does some really strange things, good that I can now replicate this:

![Screenshot from 2020-06-15 19-58-14](https://user-images.githubusercontent.com/28754793/84685362-d6858b80-af42-11ea-85dc-9f0ca490495b.png)

(the different capture level on L & R does not matter, this was just  a quick acoustical test)

**Comment by singalsu** [comment]
This was on hold while I debugged ASRC. I repeated this with current SOF git development repos:

FW 7b532d3712ff15c523f4dd52462f19aac5130e61
kernel f6be3797f3218f9fa34371000682caefbd183538

The firmware PGA5.0 gain is sane. I traced volume volume channels 0 and 1 gains in every copy(), at 1 ms rate. The 400 ms ramp as defined in topology is similar for both channels without gain jumps.

![Screenshot from 2020-07-02 15-36-40](https://user-images.githubusercontent.com/28754793/86360725-70f00980-bc7b-11ea-85e1-154d24ebab43.png)

Still the captured level envolope shows strange gain changes for both channels at 50 ms, 80ms, and for channel 0 only at 300 ms. The FW ramp envelope can be seen to last for both channels 400 ms that matches with previous plot.

![Screenshot from 2020-07-02 15-35-45](https://user-images.githubusercontent.com/28754793/86360748-7a797180-bc7b-11ea-95a8-27aaed46031c.png)

The capture pipeline contains a 40 Hz high-pass IIR filter as it should. The low frequency down and up and down waveform is from DC signal that is emitted by the codec. I'll do a capture test with pipeline without IIR so it becomes better visisible.

**Comment by singalsu** [comment]
The capture with IIR removed from pipeline looks like this:

![Screenshot from 2020-07-02 15-59-44](https://user-images.githubusercontent.com/28754793/86361891-27082300-bc7d-11ea-8db6-34a884aece34.png)

The same gain changes can be seen as above but they "ride" above the huge DC level variation in the first 500 ms of the capture. Note: This picture is with less gain than the previous with IIR.

@mengdonglin @bardliao Do you happen to know contacts to codec driver developer? The control sequence that is applied to codec looks strange. It's not possible to mitigate any further the capture start artifacts with firmware than this.

**Comment by bardliao** [comment]
@jack-cy-yu Can you help on it? Thanks.

**Comment by jack-cy-yu** [comment]
@bardliao @singalsu I've disscussed internally with system engineer for this issue, they think the pop noise is caused by DC value in DMIC, it needs some time to calibrate from its DC value to 0 by codec's filter. This issue had been reported before, are these two the same issue? https://github.com/thesofproject/linux/issues/1480

**Comment by singalsu** [comment]
@jack-cy-yu Thanks for response. What do you think about the gain variations in the data from codec. The gain variation is well visible when the high-pass filter in SOF is enabled, not the screenshot above (IIR off) but the one above (IIR enabled). I saw likely codec gain changes at 50 ms, 80 ms, and the last one 300-400 ms from capture start. The last gain change does not always happen for both channels that is strange.

I just used my phone to playback sine wave so the SPL seen by the two microphones is not the same. But I kept steady, about 10 cm, distance from phone to microphones center so the captured level should be quite stable except for the 400 ms linear ramp that SOF FW does.

**Comment by jack-cy-yu** [comment]
@singalsu  According to internal opinion, this codec gain from 0ms to 350ms is an expected result when using dmic and the time period varies from different dmic. Back to #1480 , do you know if there are dmic model differences between #1480  and this issue? (i.e. if this two issues are verified based on the same dmic)  Because different dmic might meed different settle time for dc value calibration. Second, in #1480 , you said "it can be seen that a high-pass IIR would fix this.", is the high-pass IIR really fix the pop or it just shorten the DC settle time for dmic? From our HW engineer's opinion, high-pass IIR can only shorten the settle time and isn't possible to remove settle time from beginning.

**Comment by bardliao** [comment]
> @singalsu According to internal opinion, this codec gain from 0ms to 350ms is an expected result when using dmic and the time period varies from different dmic.

@jack-cy-yu Are you saying it is a HW limitation? Can we fix it on codec driver? The patch below works on my side. You may want to move the delay to a better position. Maybe we can use module_param to adjust the delay time for different projects. 
```patch
diff --git a/sound/soc/codecs/rt715.c b/sound/soc/codecs/rt715.c
index 099c8bd20006..0a9e75e0b445 100644
--- a/sound/soc/codecs/rt715.c
+++ b/sound/soc/codecs/rt715.c
@@ -498,6 +498,7 @@ static int rt715_set_bias_level(struct snd_soc_component *component,
                        regmap_write(rt715->regmap,
                                                RT715_SET_AUDIO_POWER_STATE,
                                                AC_PWRST_D0);
+                       msleep(500);
                }
                break;
```

@singalsu Can you test the patch on your side?

**Comment by singalsu** [comment]
@bardliao Sure, thanks for the patch! I'll borrow the device and test.

**Comment by singalsu** [comment]
@bard @jack-cy-yu In my test here applying your patch fixes the capture start: Here's 355c0de437108303f1210719c4803a9766034529 without the fix:

![Screenshot from 2020-08-14 18-56-20](https://user-images.githubusercontent.com/28754793/90268593-e98fdb80-de5f-11ea-8e94-5762bfad2cd8.png)

And here's with your fix included. It looks nice:

![Screenshot from 2020-08-14 18-56-35](https://user-images.githubusercontent.com/28754793/90268627-fa405180-de5f-11ea-9daa-fe6311094efb.png)

**Comment by bardliao** [comment]
Fixed by https://github.com/thesofproject/linux/pull/2358
