### ISSUE TITLE
[BUG][CML-H] Warning "soc_dpcm_fe_runtime_update doesn't support Multi CPU yet" info shows in dmesg.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1970]
**Describe the bug**
Warning "soc_dpcm_fe_runtime_update doesn't support Multi CPU yet" info shows in dmesg. Function can't be effected when this info displayed.

**To Reproduce**
1.Boot up system successfully.
2.Check the dmesg.

**Reproduce rate**
5/5

**Expected result**
"soc_dpcm_fe_runtime_update doesn't support Multi CPU yet" info should not show in dmesg.

**Actual result**
Warning "soc_dpcm_fe_runtime_update doesn't support Multi CPU yet" info shows in dmesg.

```
[    4.374101] intel-master sdw-master-1: sdw_deprepare_stream: failed -22
[    4.374103] sdw_deprepare_stream: subdevice #0-Playback: inconsistent state state 1
[    4.374106] intel-master sdw-master-2: sdw_deprepare_stream: failed -22
[    4.374214] sof-audio-pci 0000:00:1f.3: pcm: close stream 2 dir 0
[    4.377065] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    4.377464] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    4.378557]  SDW1-Playback: soc_dpcm_fe_runtime_update doesn't support Multi CPU yet
[    4.382991]  SDW1-Playback: soc_dpcm_fe_runtime_update doesn't support Multi CPU yet
[    4.383024]  SDW1-Playback: soc_dpcm_fe_runtime_update doesn't support Multi CPU yet
[    4.384915] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    4.385211] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    4.385237] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    4.385526] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    4.386336] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[    4.386339] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[    4.386341] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[    4.386342] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:https://github.com/thesofproject/linux/commit/3bdd89d2d14f841700eb219e97c22a55aa414da0
FW: https://github.com/thesofproject/sof/commits/master commit: https://github.com/thesofproject/sof/commit/1e39ceec78b6150f4567e2631bc380762351bbdc
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

[dmesg04.log](https://github.com/thesofproject/linux/files/4413099/dmesg04.log)

**Comment by plbossart** [comment]
@sinahuang you are looking at the wrong part of the dmesg, there is an earlier issue

````
[    4.374101] intel-master sdw-master-1: sdw_deprepare_stream: failed -22
[    4.374103] sdw_deprepare_stream: subdevice #0-Playback: inconsistent state state 1
[    4.374106] intel-master sdw-master-2: sdw_deprepare_stream: failed -22
````

**Comment by sinahuang** [comment]
Yes, tracked another earlier issue by https://github.com/thesofproject/sof/issues/2690

**Comment by sinahuang** [comment]
Issue still can be reproduced on CML-H with latest sof-dev(https://github.com/thesofproject/linux/commit/866e4d555eb82bc3e4ce3ac03baff04bd2d68fb4) +master (https://github.com/thesofproject/sof/commit/90ddae9ebe6abbb331a1833a9eacb2d0505865f8)

**Comment by plbossart** [comment]
Can you try with PR #2070 ?

**Comment by sinahuang** [comment]
Check with PR https://github.com/thesofproject/linux/pull/2070, aplay -l display "no soundcard", dmesg shows "ASoC: can't create pcm iDisp1 :-22".

```
[    2.829406] rt715 sdw:3:25d:715:0: sdw_modify_slave_status: signaling completion for Slave 1
[    2.831969] snd_hda_codec_hdmi ehdaudio0D2: hdmi: pcm_num set to 3
[    2.831972] sof-audio-pci 0000:00:1f.3: display power disable
[    2.832024] sof_sdw sof_sdw: rt711-aif1 <-> SDW0 Pin2 mapping ok
[    2.832028] sof_sdw sof_sdw: rt711-aif1 <-> SDW0 Pin3 mapping ok
[    2.832040] sof_sdw sof_sdw: multicodec <-> multicpu mapping ok
[    2.832044] sof_sdw sof_sdw: rt715-aif2 <-> SDW3 Pin2 mapping ok
[    2.832047] sof_sdw sof_sdw: CPU DAI iDisp1 Pin for rtd iDisp1 does not support capture
[    2.832050] sof_sdw sof_sdw: ASoC: can't create pcm iDisp1 :-22
[    2.832155] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[    2.832165] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.832178] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[    2.832195] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[    2.832201] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
```
[dmesg1.log](https://github.com/thesofproject/linux/files/4693058/dmesg1.log)

**Comment by plbossart** [comment]
@sinahuang can you please re-check, the error with HDMI was fixed, thank you.

**Comment by sinahuang** [comment]
Original issue still can be seen with latest sof-dev(commit:2839e03) +master (commit: b5043671) on CML-H.
[dmesg.log](https://github.com/thesofproject/linux/files/4755816/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4755817/sof_trace.log)
```
[    2.138527] sof-audio-pci 0000:00:1f.3: display power disable
[    2.144974] rt711 sdw:0:25d:711:0: Slave impl defined interrupt
[    2.178050]  SDW1-Playback: soc_dpcm_fe_runtime_update doesn't support Multi CPU yet
[    2.178062]  SDW1-Playback: soc_dpcm_fe_runtime_update doesn't support Multi CPU yet
[    2.178077] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    2.178243] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    2.178256] sof-audio-pci 0000:00:1f.3: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    2.178413] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE
```

**Comment by plbossart** [comment]
@bardliao @RanderWang can you please look into this?

**Comment by bardliao** [comment]
> @bardliao @RanderWang can you please look into this?

Yes, I will look into this.

**Comment by bardliao** [comment]
@sinahuang Can you try with #2183 ?

**Comment by bardliao** [comment]
@plbossart The ``fe`` argument in soc_dpcm_fe_runtime_update() is not only FE, but also BE. See [for_each_card_rtds](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/soc-pcm.c#L2703). And it seems that we only need to handle FE in soc_dpcm_fe_runtime_update(). So my idea is to skip BE in soc_dpcm_fe_runtime_update(). What do you think?

**Comment by sinahuang** [comment]
Error can't be reproduced with PR https://github.com/thesofproject/linux/pull/2183.

**Comment by plbossart** [comment]
No, the fix is simpler:

````c
	if (fe->num_cpus > 1) {
		dev_err(fe->dev,
			"%s doesn't support Multi CPU yet\n", __func__);
		return -EINVAL;
	}

	if (!fe->dai_link->dynamic)
		return 0;
````

we need to invert the two tests :-)
I'll send a PR later today.

**Comment by plbossart** [comment]
@sinahuang can you try with PR #2185? Thanks!

**Comment by sinahuang** [comment]
Error not seen on CML-H with  PR https://github.com/thesofproject/linux/pull/2185 +master (commit:700ca2a).

**Comment by sinahuang** [comment]
Issue can't be reproduced after PR https://github.com/thesofproject/linux/pull/2185 merged, so closed it.

**Comment by plbossart** [comment]
Thanks @sinahuang for checking!
