### ISSUE TITLE
Realtek ALC285 on Omen15. Microphone not detected

### ISSUE THREAD

**Issue by wittawatj** [thesofproject/linux#2097]
On Ubuntu 20.04, by default, sof-audio-pci is used. I only have "Dummy output" in pavucontrol. To fix this, I modified /etc/modprobe.d/alsa-base.conf and added "options snd-intel-dspcfg dsp_driver=1" so that now "snd-hda-intel" is loaded instead of sof-audio-pci. While the speakers are working fine, I do not have the internal microphone working. Could you please help?

I was sent from this thread https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1874698 to here. The thread has some information about my setup already. But please do let me know if you need more information. Thank you.

**Comment by paulstelian97** [comment]
Microphone not working on non-SOF (snd-hda-intel) is a sign of you having a DMIC (digital microphone) which is only supported in SOF.

We gotta figure out why you're getting the dummy output. Are you actually not hearing anything but are able to record stuff with the SOF driver?

**Comment by paulstelian97** [comment]
Oh, also. On the SOF driver, try to stop pulseaudio (going into multi-user mode, for example) and from the console try to play something using aplay. Let us know if you can hear sounds played back using aplay. If so, something is wrong with the UCM configuration which used by Pulseaudio and needs to be checked.

**Comment by kv2019i** [comment]
@wittawatj This seems like a known problem. On system with a discrete GPU, you need a patch to alsa-ucm that is not in 20.04. See https://bugzilla.kernel.org/show_bug.cgi?id=206085#c44

Some users have also reported freezes on these systems. A FW update is on its way to fix this. Please see https://github.com/thesofproject/linux/issues/1985

**Comment by jason77-wang** [comment]
> @wittawatj This seems like a known problem. On system with a discrete GPU, you need a patch to alsa-ucm that is not in 20.04. See https://bugzilla.kernel.org/show_bug.cgi?id=206085#c44
> 
> Some users have also reported freezes on these systems. A FW update is on its way to fix this. Please see #1985

I updated the Hdmi.conf and cherry-picked 2 patches (71cc8abb6ec705ce4efbb54e401004687d40a641 and d2ad9d6ca5b2435754a0fd811f57d30914c612ce) in the ubuntu 5.4 kernel, but there are some   HDA Analog: ASoC: hw_params BE failed -22 error in the dmesg.  https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1874698/comments/27

Then tried with updated Hdmi.conf + kernel of sof-dev branch, the sof driver failed to initialize again. https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1874698/comments/29

There are dmesg.txt attached in the comment 27 and 29.

**Comment by sealse** [comment]
I have some problems for HP-OMEN 17t bc0xxx don't work sound and microphone https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1878479
I tried testing https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1874698/comments/22
It only works linux-modules-extra-5.4.0-26-generic_5.4.0-26.30+skipv4_amd64.deb
But at the same time, the second monitor stopped working on the standard ubuntu driver nvidia-graphics-drivers-440

**Comment by wittawatj** [comment]
> Oh, also. On the SOF driver, try to stop pulseaudio (going into multi-user mode, for example) and from the console try to play something using aplay. Let us know if you can hear sounds played back using aplay. If so, something is wrong with the UCM configuration which used by Pulseaudio and needs to be checked.

Running kernel 5.4.0-28-generic on SOF driver, I have the following outputs.

> 
> arecord -l
> **** List of CAPTURE Hardware Devices ****

> aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 0: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 0: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
>   Subdevices: 1/1

pavucontrol shows dummy output. 

> inxi -Ax
> Audio:     Device-1: Intel Cannon Lake PCH cAVS vendor: Hewlett-Packard driver: sof-audio-pci bus ID: 00:1f.3 
>            Device-2: NVIDIA TU106 High Definition Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
>            bus ID: 01:00.1 
>            Sound Server: ALSA v: k5.4.0-28-generic 

Tried to kill pulseaudio. The following one cannot be killed.

>  ps aux | grep pulseaudio
> gdm         6344  0.0  0.0 1076592 14720 ?       S<sl 21:05   0:00 /usr/bin/pulseaudio --daemonize=no --log-target=journal

>  curl https://ccrma.stanford.edu/~jos/wav/bachfugue.wav | aplay

I hear nothing. pavucontrol shows some interactive moving bar, indicating that some sound is playing. But no sound. In the picture, the bottom bar is moving when the sound is playing.

![image](https://user-images.githubusercontent.com/3174873/82128168-59d38600-97b9-11ea-8921-60d5ac0b515e.png)

I'm not sure how I can test `arecord`.

[dmesg.txt](https://github.com/thesofproject/linux/files/4639073/dmesg.txt)

alsa-info: http://alsa-project.org/db/?f=2a9e03850a524ff6e29a4be9cfbbdef0b5247db4

**Comment by wittawatj** [comment]
> @wittawatj This seems like a known problem. On system with a discrete GPU, you need a patch to alsa-ucm that is not in 20.04. See https://bugzilla.kernel.org/show_bug.cgi?id=206085#c44
> 
> Some users have also reported freezes on these systems. A FW update is on its way to fix this. Please see #1985

@kv2019i Do you have advice on what I should try next? Should I try to install SOF firmware 1.5 as in #1985 ? I do not know how to install it after reading the README here https://github.com/thesofproject/sof-bin/tree/stable-v1.5 . Could you please point to other pages that give some instructions? Thanks

**Comment by jason77-wang** [comment]
@wittawatj,
the sof driver in the ubuntu kernel 5.4.0-28-generic doesn't support audio configuration without intel hdmi/dp, so please try https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1874698/comments/22 and test arecord -l & aplay -l.

And looks like the kernel can not run stable on your machine, maybe it is graphic driver's problem, you could upgrade the nvidia-driver-440 to the latest version (440.82) or uninstall the nvidia-driver and blacklist the nouveau.

**Comment by kv2019i** [comment]
@wittawatj Like @jason77-wang , you hit a known problem where SOF probe fails if the integrated graphics is disabled -- no speaker/headset either. This is fixed upstream. Please see link shared by @jason77-wang above.

**Comment by wittawatj** [comment]
@jason77-wang I tried the -26 kernel in https://people.canonical.com/~hwang4/25skipi915/v4/ . Also used the Hdmi.conf there. I put it in `/usr/share/alsa/ucm2/sof-hda-dsp`. I did not upgrade my Nvidia driver.

> arecord -l
> arecord: device_list:274: no soundcards found...
> 
> aplay -l
> aplay: device_list:274: no soundcards found...

Other things I noticed:
* `nvidia-smi` failed. It says "cannot communicate because no Nvidia driver".
* My Wifi does not work.
* Cannot adjust the screen brightness.
* Natural scrolling (with libinput) stops working.

[dmesg_v4.txt](https://github.com/thesofproject/linux/files/4643210/dmesg_v4.txt)
[try_v4.txt](https://github.com/thesofproject/linux/files/4643211/try_v4.txt)

I can also try to upgrade the Nvidia driver to  440.82 if needed. Thanks.

**Comment by jason77-wang** [comment]
@wittawatj 
According to the dmesg_v4.txt, it looks like you forgot to install the linux-modules-extra?

**Comment by jason77-wang** [comment]
And please take a look at this bug, it is about the machine HP OMEN 17t, the audio could work with skipv4 testing kernel and Hdmi.conf.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1878479

**Comment by kv2019i** [comment]
@wittawatj @jason77-wang  No update in two weeks and the SOF driver part seems to be fixed, so I'll close this. Please continue the follow-up in https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1874698
