### ISSUE TITLE
[BUG] The volume of RT711 codec does not match the actual setting

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/linux#2908]
100% reproducible on `TGLU_SKU0A32_SDCA`. Found in Internal daily test 3634, 3669, 3673, 3691. [worked well on 2021-04-26 Daily but began to fail since 2021-04-27 Daily (http://sof-ci.sh.intel.com/#/result/planresultdetail/3577)]

Test command to reproduce,
TPLG=sof-tgl-rt711-rt1316-rt714.tplg ~/sof-test/test-case/check-alsabat.sh -p hw:sofsoundwire,0 -c hw:Device,0

```
WARNING: Signal overflow!
 FAIL: Peak freq too high 2991.21 Hz
 FAIL: Peak freq too high 4985.60 Hz
 FAIL: Peak freq too high 6979.25 Hz
 FAIL: Peak freq too high 8973.63 Hz
 FAIL: Peak freq too high 10968.02 Hz
alsa-utils version 1.2.2

Entering capture thread (ALSA).
Get period size: 3000  buffer size: 24000
Recording ...
Capture completed.

BAT analysis: signal has 65536 frames at 48000 Hz, 1 channels, 2 bytes per sample.

Channel 1 - Checking for target frequency 997.00 Hz
Amplitude: 48324.8; Percentage: [147]
Detected peak at 996.83 Hz of 34.70 dB
 Total 40.1 dB from 985.84 to 1008.54 Hz
 PASS: Peak detected at target frequency
Detected peak at 2991.21 Hz of 30.61 dB
 Total 40.7 dB from 2990.48 to 2992.68 Hz
Detected peak at 4985.60 Hz of 27.59 dB
 Total 41.0 dB from 4984.86 to 4986.33 Hz
Detected peak at 6979.25 Hz of 24.11 dB
 Total 41.2 dB from 6979.25 to 6980.71 Hz
Detected peak at 8973.63 Hz of 23.49 dB
 Total 41.3 dB from 8973.63 to 8973.63 Hz
Detected peak at 10968.02 Hz of 21.42 dB
 Total 41.3 dB from 10968.02 to 10968.02 Hz
Detected at least 6 signal(s) in total

Return value is -1003
```

Using audacity to analyze the recorded file , we can get --
![image](https://user-images.githubusercontent.com/79959904/117608808-6357ba00-b191-11eb-8c1c-bdf107c1f7f0.png)
![image](https://user-images.githubusercontent.com/79959904/117608872-7ff3f200-b191-11eb-9e91-2e0100b8bd77.png)

**Comment by plbossart** [comment]
could also be that the controls changed with a previous commit so the capture may not be enabled.

https://github.com/thesofproject/linux/commit/ca5118c0c00f6bc8b7d0c82c95485159db3a5584

we'd need to make sure the mixer settings are updated, @libinyang should be able to help here.

**Comment by libinyang** [comment]
This bug is caused by FU05 volume set wrongly. After cget the FU05 volume, there is possibility the FU05 volume will be changed in next playback. It should be the codec issue. PR thesofproject/linux@ca5118c is related with FU0E and FU0F. Not sure whether there is relationship between them. I will debug on it.

**Comment by libinyang** [comment]
At first, I thought this is a bug related regmap cache issue. After disable cache, the bug still can be reproduced. Another finding is the bug can **NOT** be reproduced on my rt711-rt1316-rt714 platform.

**Comment by plbossart** [comment]
@libinyang could there be an ALSA mixer setting issue and different configurations here? I would think your platform uses UCM for ALSA mixers, but it's not clear what the CI device does.

**Comment by bardliao** [comment]
> At first, I thought this is a bug related regmap cache issue. After disable cache, the bug still can be reproduced. Another finding is the bug can **NOT** be reproduced on my rt711-rt1316-rt714 platform.

I can reproduce it on my `TGLU_SKU0A32_SDCA` device. I will take a look, too.

**Comment by bardliao** [comment]
@plbossart @libinyang The issue is that regcache_sync() does nothing in rt711_sdca_dev_resume(). And the volume value will be restored to default when the codec is unattached. #2925 should fix it.

@XiaoyunWu6666 Could you test with #2925 ?

**Comment by libinyang** [comment]
@plbossart I disabled the pulseaudio and remove the UCM, the bug still can't be reproduced on my platform.

@bardliao Thanks for root cause this issue. Your explanation makes sense. These 2 days, I was studying the regmap to find when the register 0x40400291/2 (the register controls FU05 volume) is set wrongly but failed. Then I found you have already found the root cause :). Thanks.

**Comment by keqiaozhang** [comment]
@XiaoyunWu6666 , please test with #2925.

**Comment by XiaoyunWu6666** [comment]
Okay will test it with #2925  soon

**Comment by XiaoyunWu6666** [comment]
#2925 works quite well

tested on ubuntu@sh-tglu-sku0a32-sdca-01 for 100 times. all passed

**Comment by XiaoyunWu6666** [comment]
@bardliao @libinyang  @plbossart 
Already validated #2925  can fix this issue ,should we merge #2925 and close this issue?
Thanks

**Comment by bardliao** [comment]
> @bardliao @libinyang @plbossart
> Already validated #2925 can fix this issue ,should we merge #2925 and close this issue?
> Thanks

@XiaoyunWu6666  @plbossart is off this week, let's wait for some more days. BTW, https://github.com/thesofproject/linux/pull/2928 is required, too
