### ISSUE TITLE
Speaker device lost after multiple sleep and wakes

### ISSUE THREAD

**Issue by imtangmeng** [thesofproject/linux#3389]
When the system is playing video or audio in a loop, it is found that the speaker device is probabilistically lost when the system is woken up from sleep.

I found that in my environment the problem was reproduced many times.

> The test script is as follows(Play video or music before script execution):

#！/bin/bash
count=$1
num=1
while true
do 
	sudo rtcwake -l -m mem -s 20; dmesg | egrep "error|failed|warning" >> ./S3.log 
	
	sleep 10 ; 

	num=$[$num+1]

	if [ $num -gt $count ];then
		break
	fi 
done

Environment :
· ENOVO 82F8 (LENOVO_MT_82F8_BU_idea_FM_ZhaoYang K4e-ITL) Notebook 
· Tiger Lake-LP Smart Sound Technology Audio Controller
. kernel 5.10.83

log-info: https://github.com/imtangmeng/README.md/blob/main/journactl-kernel.log

$ sudo dmesg | grep audio
kernel: sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60010000 size 20
kernel: sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 1
kernel: sof-audio-pci 0000:00:1f.3: error: set pcm hw_params after resume
kernel: sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -22
kernel:  HDA Analog: ASoC: prepare FE HDA Analog failed

**Comment by imtangmeng** [comment]
Once the speaker device is lost, if the system is not restarted, the device will remain in the lost state. 
After the system restarts, the device can be used normally.

**Comment by plbossart** [comment]
@imtangmeng you are using a very very old firmware release.
Firmware info: version 1:6:0-18fab

we've corrected multiple bugs so I can only suggest you update the firmware to 2.0

**Comment by plbossart** [comment]
Your distribution may have a way to update, otherwise do it by hand with something like:

download and upzip https://github.com/thesofproject/sof-bin/archive/refs/heads/main.zip

mv /lib/firmware/intel/sof /lib/firmware/intel/sof-backup
mv /lib/firmware/intel/sof-tplg /lib/firmware/intel/sof-tplg-backup
cd sof-bin
./install v2.0.x/v2.0

**Comment by imtangmeng** [comment]
I have update the firmware to 2.0, but I still reproduced the bug:

$ sudo dmesg | grep audio
kernel: sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
kernel: sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
kernel: sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
kernel: sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
kernel: sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
kernel: sof-audio-pci 0000:00:1f.3: use msi interrupt mode
kernel: sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
kernel: sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
kernel: sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 1
kernel: sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 6 size 0x20
kernel: sof-audio-pci 0000:00:1f.3: Firmware info: version 2:0:0-b678a
kernel: sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:17:0
kernel: sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
kernel: sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 3 size 0x30
kernel: sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 5 size 0x20
kernel: sof-audio-pci 0000:00:1f.3: Firmware info: version 2:0:0-b678a
kernel: sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:17:0
kernel: sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
kernel: sof-audio-pci 0000:00:1f.3: Topology: ABI 3:20:0 Kernel ABI 3:17:0
kernel: sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel
kernel: sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
kernel: snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC257: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
kernel: snd_hda_codec_realtek ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
kernel: snd_hda_codec_realtek ehdaudio0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
kernel: snd_hda_codec_realtek ehdaudio0D0:    mono: mono_out=0x0
kernel: snd_hda_codec_realtek ehdaudio0D0:    inputs:
kernel: snd_hda_codec_realtek ehdaudio0D0:      Mic=0x19
kernel: snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
kernel: snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
kernel: sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60010000 size 20
kernel: sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 1
kernel: sof-audio-pci 0000:00:1f.3: error: set pcm hw_params after resume
kernel: sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -22

log-info: https://github.com/imtangmeng/README.md/blob/main/journactl-kernel.log

**Comment by imtangmeng** [comment]
> Your distribution may have a way to update, otherwise do it by hand with something like:
> 
> download and upzip https://github.com/thesofproject/sof-bin/archive/refs/heads/main.zip
> 
> mv /lib/firmware/intel/sof /lib/firmware/intel/sof-backup mv /lib/firmware/intel/sof-tplg /lib/firmware/intel/sof-tplg-backup cd sof-bin ./install v2.0.x/v2.0

I have update the firmware to 2.0, but I still reproduced the bug:

$ sudo dmesg | grep audio
kernel: sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
kernel: sof-audio-pci 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
kernel: sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
kernel: sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
kernel: sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
kernel: sof-audio-pci 0000:00:1f.3: use msi interrupt mode
kernel: sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
kernel: sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
kernel: sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 1
kernel: sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 6 size 0x20
kernel: sof-audio-pci 0000:00:1f.3: Firmware info: version 2:0:0-b678a
kernel: sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:17:0
kernel: sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
kernel: sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 3 size 0x30
kernel: sof-audio-pci 0000:00:1f.3: warning: unknown sof_ext_man header type 5 size 0x20
kernel: sof-audio-pci 0000:00:1f.3: Firmware info: version 2:0:0-b678a
kernel: sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:17:0
kernel: sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
kernel: sof-audio-pci 0000:00:1f.3: Topology: ABI 3:20:0 Kernel ABI 3:17:0
kernel: sof-audio-pci 0000:00:1f.3: warn: topology ABI is more recent than kernel
kernel: sof-audio-pci 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
kernel: snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC257: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
kernel: snd_hda_codec_realtek ehdaudio0D0: speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
kernel: snd_hda_codec_realtek ehdaudio0D0: hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
kernel: snd_hda_codec_realtek ehdaudio0D0: mono: mono_out=0x0
kernel: snd_hda_codec_realtek ehdaudio0D0: inputs:
kernel: snd_hda_codec_realtek ehdaudio0D0: Mic=0x19
kernel: snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
kernel: snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
kernel: sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60010000 size 20
kernel: sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 1
kernel: sof-audio-pci 0000:00:1f.3: error: set pcm hw_params after resume
kernel: sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -22

log-info: https://github.com/imtangmeng/README.md/blob/main/journactl-kernel.log

**Comment by imtangmeng** [comment]
> @imtangmeng you are using a very very old firmware release. Firmware info: version 1:6:0-18fab
> 
> we've corrected multiple bugs so I can only suggest you update the firmware to 2.0

Unfortunately, after switching to 2.0, the bug reproduced faster.

**Comment by imtangmeng** [comment]
Use the pavucontrol command to observe that when the bug recurs, the sound input and output devices are lost.

When the bug recurs, I can still get the following information.
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ lspci -nn | grep audio
0000:00:1f.3 Multimedia audio controller [0401]: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller [8086:a0c8] (rev 20)

**Comment by plbossart** [comment]
@imtangmeng Can you please copy this file [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/7934960/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf, reboot and re-test. If you see the error please attach the dmesg log. please don't copy-paste, i's going to be rather verbose. Hopefully this will give us some hints as to what happens.

**Comment by imtangmeng** [comment]
> @imtangmengCan you please copy this file sof-dyndbg.conf.txtas /etc/modprobe.d/sof-dyndbg.conf, reboot and re-test. If you see the error please attach the dmesg log. please don't copy-paste, i's going to be rather verbose. Hopefully this will give us ?some hints as to what happens.

Thanks for your help！
After copy file sof-dyndbg.conf.txt as /etc/modprobe.d/sof-dyndbg.conf, reboot and re-test.
I got the log which are as files dmesg-log-with-sof-dyndbg.log and journalctl-k.log.
$dmesg
https://github.com/imtangmeng/README.md/blob/main/dmesg-log-with-sof-dyndbg.log

$journalctl -k
https://github.com/imtangmeng/README.md/blob/main/journalctl-k.log

**Comment by plbossart** [comment]
@ranj063 @kv2019i could this be a dynamic pipeline issue with kernel 5.10?

**Comment by imtangmeng** [comment]
@ranj063 @kv2019i @plbossart Does anyone have any suggestions on how to solve this?
If needed, I can recompile the kernel to verify, or anything else I can do.

Best regards

**Comment by kv2019i** [comment]
@plbossart The error "ipc error for 0x60010000" looks a bit similar to https://github.com/thesofproject/sof/issues/5134 FYI to @ujfalusi , he just noted he could that with rtcwake as well.

**Comment by plbossart** [comment]
@imtangmeng can you try with the 5.16.1 (or later) version?

**Comment by imtangmeng** [comment]
> @imtangmeng can you try with the 5.16.1 (or later) version?

Thanks, I have used 5.16.3 to test. It seems 5.16.3 appears to be working correctly.

I think this problem may be fixed in the higher version of the kernel. At present, it is speculated that the repair patch should be the patch mentioned in https://github.com/thesofproject/sof/issues/5168, but the patch needs to be adapted and introduced in  Prefix. I will try to adapt and verify later.

Of course, if anyone has any advice on this, I'll try that too.

Since I'm about to start my Chinese New Year holiday, it may take a while to adapt to the job.

I will consider bringing the device and hopefully this will be resolved sooner rather than later. I would be very grateful for any advice on patches.

Thanks for the heads up!
Best regards

**Comment by kv2019i** [comment]
If 5.16.3 and upstream have the fixed, we can close this right @imtangmeng ?

**Comment by imtangmeng** [comment]
5.16.3 appears to be working correctly.

**Comment by imtangmeng** [comment]
This issue has been determined to be fixed in commit 619764cc2ec9ce1283a8bbcd89a1376a7c68293b and edca7cc4b0accfa69dc032442fe0684e59c691b8 upstream.

Thanks for the heads up!
Best regards
