### ISSUE TITLE
[BUG] No audio output on HP Laptop 17-cn0xxx

### ISSUE THREAD

**Issue by Zacharymk1213** [thesofproject/linux#3466]
**Describe the bug**
On my HP Laptop 17-cn0xxx the audio does not work on Linux using the latest Linux Firmware release. The audio worked in a prior release in August and as recently as a few months ago but that driver may've been highly unstable because back then the system would completely freeze to the extent that no logs were recorded I don't know what the cause was. The current Linux-firmware release does not cause this freezing issue but no audio output is produced as no soundcards are detected.
What have you tried to diagnose or workaround this issue?
I've run speaker tests at the hardware level and determined that the issue was that the soundcard wasn't being detected.

**To Reproduce**
Steps to reproduce the behavior: (e.g. list commands or actions used to reproduce the bug)
Try to play any audio on an HP Laptop 17-cn0xxx laptop.
**Reproduction Rate**
How often does the issue happen ? i.e. 1/10 (once in ten attempts), 1/1000 or all the time.
Does the reproduction rate vary with any other configuration or user action, if so please describe and show the new reproduction rate.
All the time.
**Expected behavior**
I expected to hear audio from the browser or, at least, the speaker tests and none happened.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper) showstopper. I have to use my Windows partition until this is fixed.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
I don't know how to find a commit hash, so I'm putting everything I know here.
    * Kernel: {Mainline}
    * SOF: {Early February release, linux-firmware 20220209.6342082-1}
2) Name of the topology file
I don't know what a topology file is.
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {Arch Linux}

If anyone can explain what the stuff I don't know is or how I can provide any further information please tell me.

**Comment by lgirdwood** [comment]
@ZacharyTheGamer200 can you provide your dmesg output at boot and then any dmesg output after playback with aplay.

**Comment by Zacharymk1213** [comment]
Here's the output immediately after boot after typing sudo dmesg: https://termbin.com/au1m
For dmesg output I downloaded some random dummy wav file from here https://file-examples.com/index.php/sample-audio-files/sample-wav-download/. After playing that the dmesg output is as follows: https://termbin.com/r5v8

**Comment by lgirdwood** [comment]
@ZacharyTheGamer200 it looks like we are missing a component driver (amey the codec) see.
```
[    1.277117] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    1.277138] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    1.319345] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    1.319363] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    1.319377] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
[    1.319544] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    1.319594] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    1.324307] Userspace governor deprecated: use thermal netlink notification instead
[    1.325888] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[    1.336112] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #0 probe error, ret: -2
[    1.337824] sof-audio-pci-intel-tgl 0000:00:1f.3: codec thesofproject/sof#2 probe error, ret: -2
[    1.338018] sof-audio-pci-intel-tgl 0000:00:1f.3: no hda codecs found!
[    1.338019] sof-audio-pci-intel-tgl 0000:00:1f.3: warning: No matching ASoC machine driver found
[    1.338019] sof-audio-pci-intel-tgl 0000:00:1f.3: error: no matching ASoC machine driver found - aborting probe
[    1.338020] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to get machine info -19
[    1.338135] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -19
```
The HDA codec is not probing above. @plbossart @kv2019i @ujfalusi fyi.

**Comment by Zacharymk1213** [comment]
I have no experience in firmware programming so I'm curious what would a fix for this issue look like?

**Comment by lgirdwood** [comment]
> I have no experience in firmware programming so I'm curious what would a fix for this issue look like?

Its not FW issue, looks like the HDA codec is not being probed by Linux (so could be a driver issue or an integration issue around NV audio) ? See.
```
[    0.084703] ACPI: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
```

**Comment by Zacharymk1213** [comment]
Are there any other commands I could execute or tests I could run to diagnose the exact cause of the HDA codec not being probed? (namely, whether the issue is the drivers or the integration.)

**Comment by ujfalusi** [comment]
@ZacharyTheGamer200, can you enable the dynamic debugging [1] and share the dmesg?

[1] https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html?highlight=dyndbg#enable-dynamic-debug

**Comment by ujfalusi** [comment]
@ZacharyTheGamer200, you mentioned that audio worked before on the laptop. Can you roll back `sof-firmware` or the `linux` package to see which might have caused the regression?

There were a brief regression with 5.16, but it got resolved with 5.16.3.

**Comment by Zacharymk1213** [comment]
To ensure I have all the correct options enabled here's a printout of my /etc/modprobe.d/sof-dyndbg.conf: https://termbin.com/c3qp
Here's the dmesg before attempting to play any audio:https://termbin.com/2quq
After attempting to play some audio from youtube: https://termbin.com/89mh
I'm playing around with downgrading sof-firmware and will report back.

**Comment by Zacharymk1213** [comment]
I tried downgrading to sof-firmware 1.9.1 which I think I used on the prior install but that didn't fix it. I'm going to try downgrading to Linux 5.16.3 now.

**Comment by Zacharymk1213** [comment]
Downgrading to Linux 5.16.3 as well didn't fix anything.

**Comment by ujfalusi** [comment]
@ZacharyTheGamer200, do you have sound card at all? what does `cat /proc/asound/cards` show?
Can you share the output of `alsa-info.sh` as well? Also the output of `lspci`.

The audio probe aborts because probing of the two HDA codec fails and because of that we can not find the correct machine driver. Interestingly the debugprints from `snd-sof-intel-hda-common` is still missing.

Is this laptop have NVIDIA gpu?

**Comment by Zacharymk1213** [comment]
running `cat /proc/asound/cards` results in `--- no soundcards ---`
When I run alsa-info it prints this: https://termbin.com/vu8s plus in the terminal it says `/usr/bin/alsa-info.sh: line 661: tree: command not found`
Here's the output of lspci: https://termbin.com/rkc1
The Laptop does not have an NVIDIA GPU as far as I know.

**Comment by plbossart** [comment]
@ZacharyTheGamer200 if you have HDAudio issues, you first need to try the HDaudio legacy driver. see https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html

please add this to /etc/modprobe.d/alsa-base.conf

options snd-intel-dspcfg dsp_driver=1

reboot and report the log of 'alsa-info'

Thanks!

**Comment by ujfalusi** [comment]
@ZacharyTheGamer200, for the alsa-info.sh error: `sudo pacman -S tree`

**Comment by Zacharymk1213** [comment]
So you can verify I edited the alsa-base.conf file correctly: https://termbin.com/6t4hm
Output of alsa-info after doing this edit and rebooting: https://termbin.com/mm2l 
The output of the file alsa-info produced: https://termbin.com/lm80
Thanks @ujfalusi for helping me resolve the error.

**Comment by ujfalusi** [comment]
> So you can verify I edited the alsa-base.conf file correctly: https://termbin.com/6t4hm Output of alsa-info after doing this edit and rebooting: https://termbin.com/mm2l The output of the file alsa-info produced: https://termbin.com/lm80 Thanks @ujfalusi for helping me resolve the error.

@ZacharyTheGamer200, can you also share the content of the alsa-info report?
"Your ALSA information is in `/tmp/alsa-info.txt.some_random_characters`"
`cat /tmp/alsa-info.txt.some_random_characters`
It was `/tmp/alsa-info.txt.0KpwuC9uPU` in the latest log you have shared.

Thanks

**Comment by ujfalusi** [comment]
> > So you can verify I edited the alsa-base.conf file correctly: https://termbin.com/6t4hm Output of alsa-info after doing this edit and rebooting: https://termbin.com/mm2l The output of the file alsa-info produced: https://termbin.com/lm80 Thanks @ujfalusi for helping me resolve the error.
> 
> @ZacharyTheGamer200, can you also share the content of the alsa-info report? "Your ALSA information is in `/tmp/alsa-info.txt.some_random_characters`" `cat /tmp/alsa-info.txt.some_random_characters` It was `/tmp/alsa-info.txt.0KpwuC9uPU` in the latest log you have shared.
> 
> Thanks

Nevermind, the third text is the content.

**Comment by ujfalusi** [comment]
The two HDA code is 10ec0236 (Realtek ALC3204) and 80862812 (HDMI)
In your logs:
```
[    1.534367] sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0236
[    1.535186] hdaudio ehdaudio0D0: loading codec module: hdaudio:v10EC0236r00100002a01

[    1.535869] hdaudio ehdaudio0D0: loading codec module: snd-hda-codec-generic
[    1.536513] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #0 probe error, ret: -2
[    1.536619] sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec thesofproject/sof#2 probed OK: response: 80862812
[    1.537317] hdaudio ehdaudio0D2: loading codec module: hdaudio:v80862812r00100000a01

[    1.538095] hdaudio ehdaudio0D2: loading codec module: snd-hda-codec-generic
[    1.538624] sof-audio-pci-intel-tgl 0000:00:1f.3: codec thesofproject/sof#2 probe error, ret: -2
[    1.538758] sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 0 -> 1
[    1.538892] sof-audio-pci-intel-tgl 0000:00:1f.3: no hda codecs found!
```
It is still probing the SOF driver instead of the legacy HDA.

I do have a laptop with the same codec (it is a Dell laptop) it probes just fine (but I'm forcing the SOF driver):
```
[  181.193077] sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0236
[  181.194144] hdaudio ehdaudio0D0: loading codec module: hdaudio:v10EC0236r00100002a01

[  181.202237] sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec thesofproject/sof#2 probed OK: response: 80862812
[  181.203017] hdaudio ehdaudio0D2: loading codec module: hdaudio:v80862812r00100000a01
```

I think the reason is that intel-dspcfg is in both alsa-base.conf and in sof-dyndbg.conf. Sorry about the hassle, but can you:
`rm /etc/modprobe.d/alsa-base.conf`
and edit the `/etc/modprobe.d/sof-dyndbg.conf` file, add the driver selection to the existing line, so it will look like this:
`options snd_intel_dspcfg dyndbg=+p dsp_driver=1`

In addition, can you enabled the dynamic debugging fort he HDA drivers to get some hints from there:
```
options snd-hda-codec-realtek dyndbg=+p
options snd-hda-codec-generic dyndbg=+p
options snd-hda-codec-hdmi dyndbg=+p
options snd-hda-intel dyndbg=+p
options snd-hda-codec dyndbg=+p
```
And reboot.

**Comment by ujfalusi** [comment]
@ZacharyTheGamer200, fwiw the distro kernel I'm using is `5.16.10-artix1-1` (Artix == Arch w/o systemd)

**Comment by kv2019i** [comment]
HDA codecs not probing is a driver issue, moving.

**Comment by Zacharymk1213** [comment]
Contents of `/etc/modprobe.d/sof-dyndbg.conf` after editing and reboot (for some reason doing this just broke my computer and made Arch unable to find my file system with some UUID=xxx not found error and when I plugged in a USB to live-boot and fix it it magically fixed itself without me even booting into the live environment): https://termbin.com/w12t
dmesg before playing audio:https://termbin.com/qnly
dmesg after playing audio:https://termbin.com/87kx
@ujfalusi  Distro Kernel I'm using is `linux-5.16.11.arch1-1`

**Comment by kv2019i** [comment]
@ZacharyTheGamer200 wrotE:
[    1.491294] sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0236
[    1.492262] hdaudio ehdaudio0D0: loading codec module: hdaudio:v10EC0236r00100002a01

[    1.492956] hdaudio ehdaudio0D0: loading codec module: snd-hda-codec-generic
[    1.493602] sof-audio-pci-intel-tgl 0000:00:1f.3: codec #0 probe error, ret: -2

That means the codecs are fine but your kernel is missing the codec drivers (-2 = ENOENT). Can you try with a Fedora or Ubuntu live image to confirm hardware is ok?

**Comment by Zacharymk1213** [comment]
I'll download an Ubuntu ISO and try it. I can confirm it does work just fine on Windows though. (I have a dual-boot setup.)

**Comment by ujfalusi** [comment]
> Contents of `/etc/modprobe.d/sof-dyndbg.conf` after editing and reboot (for some reason doing this just broke my computer and made Arch unable to find my file system with some UUID=xxx not found error and when I plugged in a USB to live-boot and fix it it magically fixed itself without me even booting into the live environment): https://termbin.com/w12t dmesg before playing audio:https://termbin.com/qnly dmesg after playing audio:https://termbin.com/87kx @ujfalusi Distro Kernel I'm using is `linux-5.16.11.arch1-1`

@ZacharyTheGamer200, in your sof-dyndbg.conf you have two lines for the dspcfg:
```
options snd_intel_dspcfg dyndbg=+p
options snd_intel_dspcfg dyndbg=+p dsp_driver=1
```
Can you remove the first one and reboot?

**Comment by ujfalusi** [comment]
> That means the codecs are fine but your kernel is missing the codec drivers (-2 = ENOENT). Can you try with a Fedora or Ubuntu live image to confirm hardware is ok?

It is hard to believe that Archlinux would ship without snd-hda-codec-realtek.ko...

**Comment by Zacharymk1213** [comment]
Contents of `/etc/modprobe.d/sof-dyndbg.conf` after editing and rebooting: https://termbin.com/t0ih. That did not fix the problem. Wait I forgot to take the dmesg before trying to play audio but here it is after playing audio (not rebooting now cause downloading the Ubuntu ISO.): https://termbin.com/2sue

**Comment by ujfalusi** [comment]
@Zacharymk1213, you need to reload the drivers in order to them to pick up the changes in the module parameter changes.
Doing that by hand is pretty painful, this is why we advice a reboot after each change in the module options.

**Comment by Zacharymk1213** [comment]
OK. And I do that each time I edit the module parameters. I rebooted after making the edit to `/etc/modprobe.d/sof-dyndbg.conf` IK I should be running dmesg before and after playing audio after each boot. I forgot to run dmesg before doing the audio test on this boot. During this boot I have not made any module parameter changes.

**Comment by ujfalusi** [comment]
@Zacharymk1213, something is not quite right as the snd-intel-dspcfg is not receiving the dsp_driver=1 parameter, it still goes to autoselect and picks SOF.
```
[    1.460145] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
```

Can you run: `modinfo snd_hda_codec_realtek | grep 10EC0236` to see if the realtek codec is supported or not?
if it comes back empty, then can you share the complete output of `modinfo snd_hda_codec_realtek` ?

**Comment by Zacharymk1213** [comment]
output of `modinfo snd_hda_codec_realtek | grep 10EC0236`: https://termbin.com/omb7
It didn't come back empty but just in case it's helpful here's the output of `modinfo snd_hda_codec_realtek`:  https://termbin.com/yyqr

**Comment by Zacharymk1213** [comment]
The audio does work just fine on an Ubuntu 21.10 live USB.

**Comment by kv2019i** [comment]
It seems there is some really funky stuff happening on Arch. Based on above, correct module is installed on the system, but it's not binding to the codec. Never seen this before:
[    1.534367] sof-audio-pci-intel-tgl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0236
[    1.535186] hdaudio ehdaudio0D0: loading codec module: hdaudio:v10EC0236r00100002a01
[    1.535869] hdaudio ehdaudio0D0: loading codec module: snd-hda-codec-generic

**Comment by Zacharymk1213** [comment]
BTW, the Ubuntu 12.10 live USB suffered from the currently-solved  on the latest Linux Kernel freezing bug. I can send some footage of it if you want.

**Comment by ujfalusi** [comment]
@Zacharymk1213, do you know what kernel is used on 12.10? Can you share the dmesg log after boot?

On Arch, is this `grep -R dspcfg /etc/*` brings up other entries than the sof-dyndbg.conf ? Do you have something else under /etc/modprobe.d/ ?
It is strange that forcing the legacy driver is not working, ignored.
Do you still have linux-5.15.x cached away in /var/cache/pacman/pkg/ ? Can you try it if that is working?

**Comment by Zacharymk1213** [comment]
Dmesg after boot on the Ubuntu USB: https://termbin.com/7yw7
Dmesg after playing audio on the Ubuntu USB:https://termbin.com/1l9no
Ubuntu uses the 5.13.0-19-generic kernel
Here's the output of `grep -R dspcfg /etc/*` (note: I added a bunch of modules using hwdetect):

`/etc/mkinitcpio.conf:MODULES=(intel-gtt acpi_pad platform_profile video uvcvideo xhci-pci-renesas xhci-pci btbcm btintel btrtl btusb bluetooth acpi-cpufreq pcc-cpufreq aesni-intel crc32-pclmul crc32c-intel crct10dif-pclmul ghash-clmulni-intel cryptd crypto_simd ecdh_generic libarc4 idma64 i915 ttm intel-cstate intel-uncore coretemp i2c-i801 i2c-smbus joydev atkbd mousedev i8042 libps2 serio serio_raw sparse-keymap hid-multitouch i2c-hid-acpi i2c-hid mac_hid kvm-intel kvm videobuf2-common videobuf2-memops videobuf2-v4l2 videobuf2-vmalloc mc uvcvideo videodev mei_hdcp mei mei_pxp intel-lpss-pci intel-lpss intel_pmc_bxt intel_pmt fjes rtw88_8821c rtw88_8821ce rtw88_core rtw88_pci bluetooth mac80211 rfkill cfg80211 hp-wmi pmt_class pmt_telemetry wireless-hotkey wmi-bmof wmi intel_rapl_common intel_rapl_msr pcspkr ac97_bus snd-compress snd-hwdep snd-pcm-dmaengine snd-pcm snd-timer snd snd-hda-ext-core snd-hda-core snd-intel-dspcfg snd-intel-sdw-acpi snd-hda-codec snd-hda-intel snd-soc-hdac-hda snd-soc-acpi-intel-match snd-soc-acpi snd-soc-core snd-sof-intel-hda-common snd-sof-intel-hda snd-sof-pci-intel-tgl snd-sof-pci snd-sof snd-sof-xtensa-dsp soundcore acpi_thermal_rel int3400_thermal int3403_thermal int340x_thermal_zone processor_thermal_device processor_thermal_device_pci_legacy processor_thermal_mbox processor_thermal_rapl processor_thermal_rfim intel_powerclamp intel_soc_dts_iosf intel_tcc_cooling x86_pkg_temp_thermal tpm tpm_crb tpm_tis tpm_tis_core irqbypass iTCO_vendor_support iTCO_wdt rng-core ledtrig-audio vmd soundwire-bus soundwire-cadence soundwire-generic-allocation soundwire-intel crc16)
/etc/modprobe.d/sof-dyndbg.conf:options snd_intel_dspcfg dyndbg=+p dsp_driver=1
grep: /etc/xdg/menus/cinnamon-applications-merged: No such file or directory
`
There's two files in /etc/modprobe.d these are changedsp.conf  and sof-dyndbg.conf

I don't have Linux 5.15 cached away but I could revert it and try. Edit: Trying Linux 5.15.9 now

**Comment by Zacharymk1213** [comment]
When I try to downgrade to Linux 5.15.9 I get a ERROR: module not found: `mei_pxp' and a warning image generation may not be complete. I'll reboot once I get my Arch Live USB ready in case I need to fix this.

**Comment by ujfalusi** [comment]
I guess the mei_pxp was not yet present in 5.15.x? it is listed in your mkinitcpio.conf, so likely mkinitcpio is complaining.

**Comment by ujfalusi** [comment]
@Zacharymk1213, what is the content of your `/etc/modprobe.d/changedsp.conf ` ?

**Comment by Zacharymk1213** [comment]
`/etc/modprobe.d/changedsp.conf` is blank. Just downgraded to 5.15.9. Will reboot and report back.

**Comment by Zacharymk1213** [comment]
Downgrading the kernel didn't change anything.

**Comment by ujfalusi** [comment]
@Zacharymk1213, :(
I assume that the realtek driver is loaded: `lsmod | grep snd_hda_codec_realtek`.
@kv2019i, @plbossart, you have more knowledge what might go wrong with HDA codec driver loading and binding, do you have any idea?

It is still amazingly strange that forcing the legacy driver is not working.
We have this test repo: https://github.com/thesofproject/sof-test
which contains a script pair to remove and reload the audio drivers.
```
mkdir ~/test
cd ~/test
# sudo pacman -S git
git clone https://github.com/thesofproject/sof-test
sudo ~/test/sof-test/tools/kmod/sof_remove.sh
sudo dmesg -c
sudo ~/test/sof-test/tools/kmod/sof_insert.sh
sudo dmesg
```
It should pick up the dsp_driver=1...

**Comment by Zacharymk1213** [comment]
When I try to run sof-remove.sh I get the following plus this uploaded to termbin.com. I ran it with sudo because otherwise it was crashing:

`WARNING: running as root is not supported

Specified filename /sys/kernel/debug/sof/trace does not exist.
+ systemctl --system list-unit-files --all '*pulse*'
+ systemctl --global list-unit-files --all '*pulse*'
+ systemctl --user list-unit-files --all '*pulse*'
Failed to connect to bus: No medium found
+ systemctl --user list-units --all '*pulse*'
Failed to connect to bus: No medium found
ERROR: sof_remove.sh fails semi-randomly when pulseaudio is running

Try: sudo systemctl --global mask pulseaudio.{socket,service} and reboot.
    --global is required for session managers like "gdm"

` 
And https://termbin.com/dt5l

**Comment by plbossart** [comment]
@Zacharymk1213 this looks to me like a problematic distro configuration or something odd on the userspace side.

the Ubuntu logs show the codecs are detected
````
[   16.623471] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
````

Not sure how to help further.

**Comment by ujfalusi** [comment]
@Zacharymk1213, what about the sof_insert.sh now? It looks like all modules have been removed...

**Comment by Zacharymk1213** [comment]
Here's the output of sof-insert: https://termbin.com/a674
The output of dmesg after sof-insert: https://termbin.com/x8i0. It still seems to have the same issue.

**Comment by ujfalusi** [comment]
Hrm, there is no sign of audio drivers loading in dmesg...

**Comment by Zacharymk1213** [comment]
I'll try rebooting and see. (I just realized I hadn't done this yet.) 
Edit: Rebooted and nothing has changed.

**Comment by ujfalusi** [comment]
@Zacharymk1213, can you try one more thing:
edit the `/etc/mkinitcpio.conf` and comment out (add '#' on front) of the `MODULES=(intel-gtt acpi_pad...` line, then run
`mkinitcpio -p linux`
and reboot.
It is possible that the some of the audio drivers are loaded early from the initrd, but the realtek driver is not included in there?

long shot, but I'm out of ideas.

**Comment by Zacharymk1213** [comment]
I discovered I no longer even need the VMD module added to the Modules array. This however worked. Big thank you @ujfalusi

**Comment by Zacharymk1213** [comment]
I just updated the Arch Wiki accordingly. https://wiki.archlinux.org/title/HP_Laptop_17-cn0xxx

**Comment by ujfalusi** [comment]
@Zacharymk1213, I'm glad that it got resolved!
Btw, is there any particular reason to have this extensive MODULES list for mkinitrd? It should be as minimal as possible to unblock booting to rootfs, so ethernet, non standard disk controller driver and not much else. Everything else will be loaded automagically as the hardware discovery goes further.

The devices on the HDA bus are not visible from outside, it is not like PCI or USB bus, so audio should not be in the MODULES list or sure.

**Comment by Zacharymk1213** [comment]
I was messing around with hw-detect and I thought adding all the modules to the list was a good idea. (Noob mistake I know) Apparently it wasn't.

Currently I'm having issues with the microphone.
