### ISSUE TITLE
Multiple cases of alsa-bat failures on CML_HELIOS

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#4356]
https://sof-ci.01.org/linuxpr/PR4355/build4890/devicetest/index.html?model=CML_HEL_RT5682&testcase=check-alsabat-headset-playback

https://sof-ci.01.org/linuxpr/PR4349/build4835/devicetest/index.html?model=CML_HEL_RT5682&testcase=check-alsabat-headset-playback

Device-specific issue @fredoh9 @keqiaozhang ?

**Comment by keqiaozhang** [comment]
This issue has been fixed on sh-cml-hel-rt5682-05 after replacing the audio splitter cable with a new one.

**Comment by plbossart** [comment]
This is not fixed @keqiaozhang, see latest tests
https://sof-ci.01.org/linuxpr/PR4393/build5248/devicetest/index.html

**Comment by keqiaozhang** [comment]
Interesting, there seems to be signal interference around the device. I moved `sh-cml-hel-rt5682-05` to another position, 20 iterations passed without failures.  Please let me know If the issue recurs.
