### ISSUE TITLE
No sound - Firmware topology file missing

### ISSUE THREAD

**Issue by michalzientara** [thesofproject/linux#5380]
No sound on my asus zenbook notebook after recent software update

**HW:** ASUS Zenbook S 14 UX5406SA_UX5406SA
**Distro:** Fedora Linux 41.20250401.0 (Silverblue)
**Kernel:** Linux fedora 6.13.9-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Mar 29 01:29:31 UTC 2025 x86_64 GNU/Linux
**package:**  alsa-sof-firmware-2025.01-1.fc41.noarch

Seems topology file is missing - corrupted firmware package (?)

[   14.336917] sof-audio-pci-intel-lnl 0000:00:1f.3: SOF firmware and/or topology file not found.
[   14.336920] sof-audio-pci-intel-lnl 0000:00:1f.3: Supported default profiles
[   14.336921] sof-audio-pci-intel-lnl 0000:00:1f.3: - ipc type 1 (Requested):
[   14.336922] sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware file: intel/sof-ipc4/lnl/sof-lnl.ri
**[   14.336923] sof-audio-pci-intel-lnl 0000:00:1f.3:  Topology file: intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg**
[   14.336923] sof-audio-pci-intel-lnl 0000:00:1f.3: Check if you have 'sof-firmware' package installed.
[   14.336924] sof-audio-pci-intel-lnl 0000:00:1f.3: Optionally it can be manually downloaded from:
[   14.336924] sof-audio-pci-intel-lnl 0000:00:1f.3:    https://github.com/thesofproject/sof-bin/

**lspci -k | grep -i aud**
00:1f.3 Multimedia audio controller: Intel Corporation Lunar Lake-M HD Audio Controller (rev 10)
	Kernel driver in use: sof-audio-pci-intel-lnl

**aplay:** device_list:279: no soundcards found...

**Comment by lucasb-eyer** [comment]
Same for me. Asus Zenbook too.
It worked in the past and one of the recent kernel or sof upgrades it stops working.
I'm on arch (`6.13.8-arch1-16.13.8-arch1-1`) but see all the same errors as @michalzientara.

When I downgrade to the previous version of sof-firmware, it also didn't work, though I'm not completely confident in my downgrade skills. I noticed that the previous version had fewer tplg files (copied to my home):

-rw-r--r-- 1 root root 71K Apr  1 22:01 /home/lb/sof-lnl-cs42l43-l0-2ch.tplg
-rw-r--r-- 1 root root 70K Apr  1 22:01 /home/lb/sof-lnl-cs42l43-l0-4ch.tplg
-rw-r--r-- 1 root root 60K Apr  1 22:01 /home/lb/sof-lnl-cs42l43-l0-cs35l56-l23.tplg
-rw-r--r-- 1 root root 71K Apr  1 22:01 /home/lb/sof-lnl-cs42l43-l0-cs35l56-l3-2ch.tplg
-rw-r--r-- 1 root root 59K Apr  1 22:01 /home/lb/sof-lnl-cs42l43-l0-cs35l56-l3.tplg
-rw-r--r-- 1 root root 59K Apr  1 22:01 /home/lb/sof-lnl-cs42l43-l0.tplg

(notice the one from the error message, `l23-2ch` didn't exist) while the current version has more, including that from the error:

ll /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-*.tplg
-rw-r--r-- 1 root root 71K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-2ch.tplg
-rw-r--r-- 1 root root 70K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-4ch.tplg
-rw-r--r-- 1 root root 72K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg
-rw-r--r-- 1 root root 71K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-4ch.tplg
-rw-r--r-- 1 root root 60K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23.tplg
-rw-r--r-- 1 root root 71K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l3-2ch.tplg
-rw-r--r-- 1 root root 59K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l3.tplg
-rw-r--r-- 1 root root 59K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0.tplg
-rw-r--r-- 1 root root 62K Mar 31 18:11 /lib/firmware/intel/sof-ipc4-tplg/sof-lnl-cs42l43-l2-cs35l56x6-l13.tplg

Just for fun, I tried actually removing the file to see if anything changes, but nothing changes.

**Comment by speedlimiter** [comment]
Same here with ASUS Zenbook S 14 UX5406SA running Arch. Sound worked for the last 2-3 months and than stops after a kernel or sof-release. At first it was the missing topology file and now with a fresh Arch install it looks like in the attached dmesg.

[dmesg.txt](https://github.com/user-attachments/files/19594161/dmesg.txt)

**Comment by perexg** [comment]
According information in https://bugzilla.redhat.com/show_bug.cgi?id=2356706, the problem persists with sof firmware 2025.01.1:

```
sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware file:     intel/sof-ipc4/lnl/sof-lnl.ri
sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware lib path: intel/sof-ipc4-lib/lnl
sof-audio-pci-intel-lnl 0000:00:1f.3:  Topology file:     intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg
sof-audio-pci-intel-lnl 0000:00:1f.3: Loaded firmware library: ADSPFW, version: 2.12.0.1
sof-audio-pci-intel-lnl 0000:00:1f.3: Booted firmware version: 2.12.0.1
sof-audio-pci-intel-lnl 0000:00:1f.3: Topology: ABI 3:29:1 Kernel ABI 3:23:1
sof_sdw sof_sdw: ASoC: physical link dmic01 (id 3) not exist
sof_sdw sof_sdw: ASoC: topology: could not load header: -22
sof-audio-pci-intel-lnl 0000:00:1f.3: error: tplg component load failed -22
sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to load DSP topology -22
sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
sof_sdw sof_sdw: ASoC: failed to instantiate card -22
sof_sdw sof_sdw: error -EINVAL: snd_soc_register_card failed -22
sof_sdw sof_sdw: probe with driver sof_sdw failed with error -22
```

@kv2019i FYI

**Comment by kv2019i** [comment]
Looping in @ujfalusi @bardliao @simontrimmer  who've been debugging previous iterations. 

The topology requires this kernel patch to be included:
https://github.com/thesofproject/linux/pull/5301/commits/f026364ea45dabfe5a21280884cd8a8f994d8ac2

**Comment by perexg** [comment]
Applied to upstream as `v6.14-rc1-3-g084344970808` so it should be fixed in 6.14 kernel.

**Comment by simontrimmer** [comment]
Yes indeed - it's a bit of a pain that we needed to advance two places to make this system happier but Kernel v6.14 should contain the quirk and v2025.01.1 release of sof-bin should contain the topology

**Comment by archeoss** [comment]
with kernel v6.14 and v2025.01.1 of sof-frimware sound still doesn't work on Asus Zenbook S 16 UX5606SA. with Arch installation 
<details>
  <summary>dmesg errors</summary>
  
```
[    4.871145] sof-audio-pci-intel-lnl 0000:00:1f.3: Booted firmware version: 2.12.0.1
[    4.891216] sof_sdw sof_sdw: Both SDW DMIC and PCH DMIC are present, if incorrect, please set kernel params snd_sof_intel_hda_generic dmic_num=0 to disable PCH DMIC
[    4.891328] cs42l43-codec cs42l43-codec: supply vdd-amp not found, using dummy regulator
[    4.892523] sof-audio-pci-intel-lnl 0000:00:1f.3: Topology: ABI 3:29:1 Kernel ABI 3:23:1
[    4.892784] sof_sdw sof_sdw: ASoC: physical link dmic01 (id 3) not exist
[    4.892785] sof_sdw sof_sdw: ASoC: topology: could not load header: -22
[    4.892825] sof-audio-pci-intel-lnl 0000:00:1f.3: error: tplg component load failed -22
[    4.892828] sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to load DSP topology -22
[    4.892829] sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[    4.892840] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[    4.893978] sof_sdw sof_sdw: error -EINVAL: snd_soc_register_card failed -22
[    4.893982] sof_sdw sof_sdw: probe with driver sof_sdw failed with error -22
```
  
</details>

<details>
  <summary>other dmesg info</summary>

[    4.451216] snd_hda_intel 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[    4.543734] sof-audio-pci-intel-lnl 0000:00:1f.3: enabling device (0000 -> 0002)
[    4.543839] sof-audio-pci-intel-lnl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.543873] sof-audio-pci-intel-lnl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [xe])
[    4.552016] sof-audio-pci-intel-lnl 0000:00:1f.3: use msi interrupt mode
[    4.561825] acpi device:3d: find_sdca_function: SDCA function UAJ (type 6) at 0x3
[    4.561831] acpi device:3e: find_sdca_function: SDCA function HID (type 10) at 0x4
[    4.561959] acpi device:35: find_sdca_function: SDCA function SmartAmp (type 1) at 0x1
[    4.562027] acpi device:37: find_sdca_function: SDCA function SmartAmp (type 1) at 0x1
[    4.562162] acpi device:39: find_sdca_function: SDCA function SmartAmp (type 1) at 0x1
[    4.562227] acpi device:3b: find_sdca_function: SDCA function SmartAmp (type 1) at 0x1
[    4.571408] sof-audio-pci-intel-lnl 0000:00:1f.3: hda codecs found, mask 4
[    4.571412] sof-audio-pci-intel-lnl 0000:00:1f.3: NHLT device BT(0) detected, ssp_mask 0x4
[    4.571414] sof-audio-pci-intel-lnl 0000:00:1f.3: BT link detected in NHLT tables: 0x4
[    4.571415] sof-audio-pci-intel-lnl 0000:00:1f.3: DMICs detected in NHLT tables: 4
[    4.573623] sof-audio-pci-intel-lnl 0000:00:1f.3: Firmware paths/files for ipc type 1:
[    4.573624] sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware file:     intel/sof-ipc4/lnl/sof-lnl.ri
[    4.573625] sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware lib path: intel/sof-ipc4-lib/lnl
[    4.573625] sof-audio-pci-intel-lnl 0000:00:1f.3:  Topology file:     intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-4ch.tplg
[    4.573951] sof-audio-pci-intel-lnl 0000:00:1f.3: Loaded firmware library: ADSPFW, version: 2.12.0.1
[    4.577057] cs42l43 sdw:0:0:01fa:4243:01: supply vdd-p not found, using dummy regulator
[    4.577093] cs42l43 sdw:0:0:01fa:4243:01: supply vdd-d not found, using dummy regulator
[    4.577099] cs42l43 sdw:0:0:01fa:4243:01: supply vdd-a not found, using dummy regulator
[    4.577104] cs42l43 sdw:0:0:01fa:4243:01: supply vdd-io not found, using dummy regulator
[    4.577108] cs42l43 sdw:0:0:01fa:4243:01: supply vdd-cp not found, using dummy regulator
[    4.579563] cs42l43 sdw:0:0:01fa:4243:01: devid: 0x042a43, rev: 0xa1, otp: 0x03
[    4.580288] cs35l56 sdw:0:2:01fa:3556:01:0: supply VDD_P not found, using dummy regulator
[    4.580313] cs35l56 sdw:0:2:01fa:3556:01:0: supply VDD_IO not found, using dummy regulator
[    4.580321] cs35l56 sdw:0:2:01fa:3556:01:0: supply VDD_A not found, using dummy regulator
[    4.588392] cs35l56 sdw:0:2:01fa:3556:01:0: Cirrus Logic CS35L56 Rev B0 OTP3 fw:3.4.4 (patched=0)
[    4.594919] cs35l56 sdw:0:2:01fa:3556:01:0: Slave 2 state check1: UNATTACHED, status was 1
[    4.594996] cs35l56 sdw:0:2:01fa:3556:01:1: supply VDD_P not found, using dummy regulator
[    4.595021] cs35l56 sdw:0:2:01fa:3556:01:1: supply VDD_IO not found, using dummy regulator
[    4.595029] cs35l56 sdw:0:2:01fa:3556:01:1: supply VDD_A not found, using dummy regulator
[    4.601047] cs42l43 sdw:0:0:01fa:4243:01: Slave 6 state check1: UNATTACHED, status was 1
[    4.602096] cs35l56 sdw:0:2:01fa:3556:01:1: Cirrus Logic CS35L56 Rev B0 OTP3 fw:3.4.4 (patched=0)
[    4.608606] cs35l56 sdw:0:3:01fa:3556:01:2: supply VDD_P not found, using dummy regulator
[    4.608639] cs35l56 sdw:0:3:01fa:3556:01:2: supply VDD_IO not found, using dummy regulator
[    4.608649] cs35l56 sdw:0:3:01fa:3556:01:2: supply VDD_A not found, using dummy regulator
[    4.615152] cs35l56 sdw:0:2:01fa:3556:01:1: Slave 1 state check1: UNATTACHED, status was 1
[    4.616161] cs35l56 sdw:0:3:01fa:3556:01:2: Cirrus Logic CS35L56 Rev B0 OTP3 fw:3.4.4 (patched=0)
[    4.622755] cs35l56 sdw:0:3:01fa:3556:01:2: Slave 2 state check1: UNATTACHED, status was 1
[    4.622803] cs35l56 sdw:0:3:01fa:3556:01:3: supply VDD_P not found, using dummy regulator
[    4.622837] cs35l56 sdw:0:3:01fa:3556:01:3: supply VDD_IO not found, using dummy regulator
[    4.622846] cs35l56 sdw:0:3:01fa:3556:01:3: supply VDD_A not found, using dummy regulator
[    4.624967] Adding alias for supply vdd-amp,(null) -> vdd-amp,sdw:0:0:01fa:4243:01
[    4.630144] cs35l56 sdw:0:3:01fa:3556:01:3: Cirrus Logic CS35L56 Rev B0 OTP3 fw:3.4.4 (patched=0)
[    4.643293] cs35l56 sdw:0:3:01fa:3556:01:3: Slave 1 state check1: UNATTACHED, status was 1
[    4.871145] sof-audio-pci-intel-lnl 0000:00:1f.3: Booted firmware version: 2.12.0.1
[    4.891216] sof_sdw sof_sdw: Both SDW DMIC and PCH DMIC are present, if incorrect, please set kernel params snd_sof_intel_hda_generic dmic_num=0 to disable PCH DMIC
[    4.891328] cs42l43-codec cs42l43-codec: supply vdd-amp not found, using dummy regulator
[    4.892523] sof-audio-pci-intel-lnl 0000:00:1f.3: Topology: ABI 3:29:1 Kernel ABI 3:23:1
[    4.892784] sof_sdw sof_sdw: ASoC: physical link dmic01 (id 3) not exist
[    4.892785] sof_sdw sof_sdw: ASoC: topology: could not load header: -22
[    4.892825] sof-audio-pci-intel-lnl 0000:00:1f.3: error: tplg component load failed -22
[    4.892828] sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to load DSP topology -22
[    4.892829] sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[    4.892840] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[    4.893978] sof_sdw sof_sdw: error -EINVAL: snd_soc_register_card failed -22
[    4.893982] sof_sdw sof_sdw: probe with driver sof_sdw failed with error -22

</details>

**lspci -k | grep -i aud:**

00:1f.3 Multimedia audio controller: Intel Corporation Lunar Lake-M HD Audio Controller (rev 10)
        Kernel driver in use: sof-audio-pci-intel-lnl

**aplay -l:**

aplay: device_list:279: no soundcards found...

**uname -r:**

6.14.1-arch1-1

**pacman -Qqi sof-firmware | grep Version**

Version         : 2025.01.1-1

**Comment by archeoss** [comment]
If someone discovered this issue and ran into similar issues, but with the Zenbook S16 UX5606SA, it looks like we should wait for the 6.15 kernel release or any other stable branch, which will contain the patch for UX5606 https://github.com/thesofproject/sof/issues/9930

**Comment by ujfalusi** [comment]
@archeoss, the kernel patch [1] is going to be backported to 6.14 after it is applied to mainline.

[1] https://lore.kernel.org/linux-sound/20250404133213.4658-1-peter.ujfalusi@linux.intel.com/

**Comment by sdwerwed** [comment]
I was able to make audio work on `ASUS Zenbook S 14 (UX5406)` by following https://github.com/dantmnf/zenbook-s14-linux?tab=readme-ov-file#microphone-array-dmic. I use last kernel 6.14.0-1-default and sof-firmware

``` dmesg | grep -i sof
[    0.014151] [      T0] software IO TLB: area num 8.
[    0.539187] [      T1] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.579430] [      T1] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.579431] [      T1] software IO TLB: mapped [mem 0x000000004f89a000-0x000000005389a000] (64MB)
[    0.750475] [      T1] integrity: Loaded X.509 cert 'Microsoft Corporation UEFI CA 2011: 13adbf4309bd82709c8cd54f316ed522988a1bd4'
[    0.750492] [      T1] integrity: Loaded X.509 cert 'Microsoft Windows Production PCA 2011: a92902398e16c49778cd90f99e4f9ae17c55af53'
[    0.750512] [      T1] integrity: Loaded X.509 cert 'Microsoft Corporation: Windows UEFI CA 2023: aefc5fbbbe055d8f8daa585473499417ab5a5272'
[    0.750526] [      T1] integrity: Loaded X.509 cert 'Microsoft UEFI CA 2023: 81aa6b3244c935bce0d6628af39827421e32497d'
[    5.144056] [    T731] sof-audio-pci-intel-lnl 0000:00:1f.3: enabling device (0000 -> 0002)
[    5.144164] [    T731] sof-audio-pci-intel-lnl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    5.144222] [    T731] sof-audio-pci-intel-lnl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [xe])
[    5.151198] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: use msi interrupt mode
[    5.169397] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: hda codecs found, mask 4
[    5.169406] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: NHLT device BT(0) detected, ssp_mask 0x4
[    5.169407] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: BT link detected in NHLT tables: 0x4
[    5.169408] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[    5.172447] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: Firmware paths/files for ipc type 1:
[    5.172449] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware file:     intel/sof-ipc4/lnl/sof-lnl.ri
[    5.172450] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3:  Firmware lib path: intel/sof-ipc4-lib/lnl
[    5.172450] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3:  Topology file:     intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg
[    5.172959] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: Loaded firmware library: ADSPFW, version: 2.12.0.1
[    5.470403] [    T558] sof-audio-pci-intel-lnl 0000:00:1f.3: Booted firmware version: 2.12.0.1
[    5.481804] [    T754] sof_sdw sof_sdw: Overriding quirk 0x20000 => 0x20041
[    5.485604] [    T754] sof-audio-pci-intel-lnl 0000:00:1f.3: Topology: ABI 3:29:1 Kernel ABI 3:23:1
[    5.486359] [    T754] sof_sdw sof_sdw: ASoC: Parent card not yet available, widget card binding deferred
[    5.487328] [    T754] sof-audio-pci-intel-lnl 0000:00:1f.3: Loaded firmware library: ADSPFW, version: 2.12.0.1
[    5.534162] [    T754] sof_sdw sof_sdw: hda_dsp_hdmi_build_controls: no PCM in topology for HDMI converter 3
[    6.760162] [    T754] input: sof-soundwire Jack as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input34
[    6.760300] [    T754] input: sof-soundwire HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input35
[    6.760386] [    T754] input: sof-soundwire HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input36
[    6.760460] [    T754] input: sof-soundwire HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card0/input37
dp@localhost:~/Downloads> 
```

**Comment by Si-Ki** [comment]
> I was able to make audio work on `ASUS Zenbook S 14 (UX5406)` by following https://github.com/dantmnf/zenbook-s14-linux?tab=readme-ov-file#microphone-array-dmic. I use last kernel 6.14.0-1-default and sof-firmware
>

by following the guide... did you mean, downgrading the kernel and sof-firmware pkgs?

what else did you do to make it work, talking about just the speakers; not microphone :) 

thanks

EDIT:
I did some stuff and it works now... and I have no idea what made it work, even the input is working just fine now... too tired at this point, will try to post something useful tmw :) 

good night people 🥳

**Comment by lucasb-eyer** [comment]
There was an update on arch a couple days ago which fixed ALL sound issues on my S14. Now audio out works again, and even audio in (mic) work, which never worked before.

The update didn't have a new kernel, but did have new alsa, pipewire, and maybe also drivers. So if you're on arch, just update everything. On another distro, hold tight, should be working soon!

**Comment by archeoss** [comment]
6.14.4 Kernel includes quirk for ASUS Zenbook S16 now: https://lwn.net/Articles/1018914/

Everything works fine on my machine

I guess issue can be closed

**Comment by ranj063** [comment]
@michalzientara please close this if you are able to test the new kernel. Thanks!

**Comment by michalzientara** [comment]
it works beautifully. Thank you.
